package com.gk.webmagic.demo3.model;

import java.util.ArrayList;
import java.util.List;

public class NcpssdBeanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ncpssd
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ncpssd
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ncpssd
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ncpssd
     *
     * @mbg.generated
     */
    public NcpssdBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ncpssd
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ncpssd
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ncpssd
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ncpssd
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ncpssd
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ncpssd
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ncpssd
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ncpssd
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ncpssd
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ncpssd
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ncpssd
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andManageDepartmentIsNull() {
            addCriterion("manage_department is null");
            return (Criteria) this;
        }

        public Criteria andManageDepartmentIsNotNull() {
            addCriterion("manage_department is not null");
            return (Criteria) this;
        }

        public Criteria andManageDepartmentEqualTo(String value) {
            addCriterion("manage_department =", value, "manageDepartment");
            return (Criteria) this;
        }

        public Criteria andManageDepartmentNotEqualTo(String value) {
            addCriterion("manage_department <>", value, "manageDepartment");
            return (Criteria) this;
        }

        public Criteria andManageDepartmentGreaterThan(String value) {
            addCriterion("manage_department >", value, "manageDepartment");
            return (Criteria) this;
        }

        public Criteria andManageDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("manage_department >=", value, "manageDepartment");
            return (Criteria) this;
        }

        public Criteria andManageDepartmentLessThan(String value) {
            addCriterion("manage_department <", value, "manageDepartment");
            return (Criteria) this;
        }

        public Criteria andManageDepartmentLessThanOrEqualTo(String value) {
            addCriterion("manage_department <=", value, "manageDepartment");
            return (Criteria) this;
        }

        public Criteria andManageDepartmentLike(String value) {
            addCriterion("manage_department like", value, "manageDepartment");
            return (Criteria) this;
        }

        public Criteria andManageDepartmentNotLike(String value) {
            addCriterion("manage_department not like", value, "manageDepartment");
            return (Criteria) this;
        }

        public Criteria andManageDepartmentIn(List<String> values) {
            addCriterion("manage_department in", values, "manageDepartment");
            return (Criteria) this;
        }

        public Criteria andManageDepartmentNotIn(List<String> values) {
            addCriterion("manage_department not in", values, "manageDepartment");
            return (Criteria) this;
        }

        public Criteria andManageDepartmentBetween(String value1, String value2) {
            addCriterion("manage_department between", value1, value2, "manageDepartment");
            return (Criteria) this;
        }

        public Criteria andManageDepartmentNotBetween(String value1, String value2) {
            addCriterion("manage_department not between", value1, value2, "manageDepartment");
            return (Criteria) this;
        }

        public Criteria andSponsorDepartmentIsNull() {
            addCriterion("sponsor_department is null");
            return (Criteria) this;
        }

        public Criteria andSponsorDepartmentIsNotNull() {
            addCriterion("sponsor_department is not null");
            return (Criteria) this;
        }

        public Criteria andSponsorDepartmentEqualTo(String value) {
            addCriterion("sponsor_department =", value, "sponsorDepartment");
            return (Criteria) this;
        }

        public Criteria andSponsorDepartmentNotEqualTo(String value) {
            addCriterion("sponsor_department <>", value, "sponsorDepartment");
            return (Criteria) this;
        }

        public Criteria andSponsorDepartmentGreaterThan(String value) {
            addCriterion("sponsor_department >", value, "sponsorDepartment");
            return (Criteria) this;
        }

        public Criteria andSponsorDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("sponsor_department >=", value, "sponsorDepartment");
            return (Criteria) this;
        }

        public Criteria andSponsorDepartmentLessThan(String value) {
            addCriterion("sponsor_department <", value, "sponsorDepartment");
            return (Criteria) this;
        }

        public Criteria andSponsorDepartmentLessThanOrEqualTo(String value) {
            addCriterion("sponsor_department <=", value, "sponsorDepartment");
            return (Criteria) this;
        }

        public Criteria andSponsorDepartmentLike(String value) {
            addCriterion("sponsor_department like", value, "sponsorDepartment");
            return (Criteria) this;
        }

        public Criteria andSponsorDepartmentNotLike(String value) {
            addCriterion("sponsor_department not like", value, "sponsorDepartment");
            return (Criteria) this;
        }

        public Criteria andSponsorDepartmentIn(List<String> values) {
            addCriterion("sponsor_department in", values, "sponsorDepartment");
            return (Criteria) this;
        }

        public Criteria andSponsorDepartmentNotIn(List<String> values) {
            addCriterion("sponsor_department not in", values, "sponsorDepartment");
            return (Criteria) this;
        }

        public Criteria andSponsorDepartmentBetween(String value1, String value2) {
            addCriterion("sponsor_department between", value1, value2, "sponsorDepartment");
            return (Criteria) this;
        }

        public Criteria andSponsorDepartmentNotBetween(String value1, String value2) {
            addCriterion("sponsor_department not between", value1, value2, "sponsorDepartment");
            return (Criteria) this;
        }

        public Criteria andEditorIsNull() {
            addCriterion("editor is null");
            return (Criteria) this;
        }

        public Criteria andEditorIsNotNull() {
            addCriterion("editor is not null");
            return (Criteria) this;
        }

        public Criteria andEditorEqualTo(String value) {
            addCriterion("editor =", value, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorNotEqualTo(String value) {
            addCriterion("editor <>", value, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorGreaterThan(String value) {
            addCriterion("editor >", value, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorGreaterThanOrEqualTo(String value) {
            addCriterion("editor >=", value, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorLessThan(String value) {
            addCriterion("editor <", value, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorLessThanOrEqualTo(String value) {
            addCriterion("editor <=", value, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorLike(String value) {
            addCriterion("editor like", value, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorNotLike(String value) {
            addCriterion("editor not like", value, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorIn(List<String> values) {
            addCriterion("editor in", values, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorNotIn(List<String> values) {
            addCriterion("editor not in", values, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorBetween(String value1, String value2) {
            addCriterion("editor between", value1, value2, "editor");
            return (Criteria) this;
        }

        public Criteria andEditorNotBetween(String value1, String value2) {
            addCriterion("editor not between", value1, value2, "editor");
            return (Criteria) this;
        }

        public Criteria andBuildTimeIsNull() {
            addCriterion("build_time is null");
            return (Criteria) this;
        }

        public Criteria andBuildTimeIsNotNull() {
            addCriterion("build_time is not null");
            return (Criteria) this;
        }

        public Criteria andBuildTimeEqualTo(String value) {
            addCriterion("build_time =", value, "buildTime");
            return (Criteria) this;
        }

        public Criteria andBuildTimeNotEqualTo(String value) {
            addCriterion("build_time <>", value, "buildTime");
            return (Criteria) this;
        }

        public Criteria andBuildTimeGreaterThan(String value) {
            addCriterion("build_time >", value, "buildTime");
            return (Criteria) this;
        }

        public Criteria andBuildTimeGreaterThanOrEqualTo(String value) {
            addCriterion("build_time >=", value, "buildTime");
            return (Criteria) this;
        }

        public Criteria andBuildTimeLessThan(String value) {
            addCriterion("build_time <", value, "buildTime");
            return (Criteria) this;
        }

        public Criteria andBuildTimeLessThanOrEqualTo(String value) {
            addCriterion("build_time <=", value, "buildTime");
            return (Criteria) this;
        }

        public Criteria andBuildTimeLike(String value) {
            addCriterion("build_time like", value, "buildTime");
            return (Criteria) this;
        }

        public Criteria andBuildTimeNotLike(String value) {
            addCriterion("build_time not like", value, "buildTime");
            return (Criteria) this;
        }

        public Criteria andBuildTimeIn(List<String> values) {
            addCriterion("build_time in", values, "buildTime");
            return (Criteria) this;
        }

        public Criteria andBuildTimeNotIn(List<String> values) {
            addCriterion("build_time not in", values, "buildTime");
            return (Criteria) this;
        }

        public Criteria andBuildTimeBetween(String value1, String value2) {
            addCriterion("build_time between", value1, value2, "buildTime");
            return (Criteria) this;
        }

        public Criteria andBuildTimeNotBetween(String value1, String value2) {
            addCriterion("build_time not between", value1, value2, "buildTime");
            return (Criteria) this;
        }

        public Criteria andPublishPeroidIsNull() {
            addCriterion("publish_peroid is null");
            return (Criteria) this;
        }

        public Criteria andPublishPeroidIsNotNull() {
            addCriterion("publish_peroid is not null");
            return (Criteria) this;
        }

        public Criteria andPublishPeroidEqualTo(String value) {
            addCriterion("publish_peroid =", value, "publishPeroid");
            return (Criteria) this;
        }

        public Criteria andPublishPeroidNotEqualTo(String value) {
            addCriterion("publish_peroid <>", value, "publishPeroid");
            return (Criteria) this;
        }

        public Criteria andPublishPeroidGreaterThan(String value) {
            addCriterion("publish_peroid >", value, "publishPeroid");
            return (Criteria) this;
        }

        public Criteria andPublishPeroidGreaterThanOrEqualTo(String value) {
            addCriterion("publish_peroid >=", value, "publishPeroid");
            return (Criteria) this;
        }

        public Criteria andPublishPeroidLessThan(String value) {
            addCriterion("publish_peroid <", value, "publishPeroid");
            return (Criteria) this;
        }

        public Criteria andPublishPeroidLessThanOrEqualTo(String value) {
            addCriterion("publish_peroid <=", value, "publishPeroid");
            return (Criteria) this;
        }

        public Criteria andPublishPeroidLike(String value) {
            addCriterion("publish_peroid like", value, "publishPeroid");
            return (Criteria) this;
        }

        public Criteria andPublishPeroidNotLike(String value) {
            addCriterion("publish_peroid not like", value, "publishPeroid");
            return (Criteria) this;
        }

        public Criteria andPublishPeroidIn(List<String> values) {
            addCriterion("publish_peroid in", values, "publishPeroid");
            return (Criteria) this;
        }

        public Criteria andPublishPeroidNotIn(List<String> values) {
            addCriterion("publish_peroid not in", values, "publishPeroid");
            return (Criteria) this;
        }

        public Criteria andPublishPeroidBetween(String value1, String value2) {
            addCriterion("publish_peroid between", value1, value2, "publishPeroid");
            return (Criteria) this;
        }

        public Criteria andPublishPeroidNotBetween(String value1, String value2) {
            addCriterion("publish_peroid not between", value1, value2, "publishPeroid");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andInternationalCodeIsNull() {
            addCriterion("international_code is null");
            return (Criteria) this;
        }

        public Criteria andInternationalCodeIsNotNull() {
            addCriterion("international_code is not null");
            return (Criteria) this;
        }

        public Criteria andInternationalCodeEqualTo(String value) {
            addCriterion("international_code =", value, "internationalCode");
            return (Criteria) this;
        }

        public Criteria andInternationalCodeNotEqualTo(String value) {
            addCriterion("international_code <>", value, "internationalCode");
            return (Criteria) this;
        }

        public Criteria andInternationalCodeGreaterThan(String value) {
            addCriterion("international_code >", value, "internationalCode");
            return (Criteria) this;
        }

        public Criteria andInternationalCodeGreaterThanOrEqualTo(String value) {
            addCriterion("international_code >=", value, "internationalCode");
            return (Criteria) this;
        }

        public Criteria andInternationalCodeLessThan(String value) {
            addCriterion("international_code <", value, "internationalCode");
            return (Criteria) this;
        }

        public Criteria andInternationalCodeLessThanOrEqualTo(String value) {
            addCriterion("international_code <=", value, "internationalCode");
            return (Criteria) this;
        }

        public Criteria andInternationalCodeLike(String value) {
            addCriterion("international_code like", value, "internationalCode");
            return (Criteria) this;
        }

        public Criteria andInternationalCodeNotLike(String value) {
            addCriterion("international_code not like", value, "internationalCode");
            return (Criteria) this;
        }

        public Criteria andInternationalCodeIn(List<String> values) {
            addCriterion("international_code in", values, "internationalCode");
            return (Criteria) this;
        }

        public Criteria andInternationalCodeNotIn(List<String> values) {
            addCriterion("international_code not in", values, "internationalCode");
            return (Criteria) this;
        }

        public Criteria andInternationalCodeBetween(String value1, String value2) {
            addCriterion("international_code between", value1, value2, "internationalCode");
            return (Criteria) this;
        }

        public Criteria andInternationalCodeNotBetween(String value1, String value2) {
            addCriterion("international_code not between", value1, value2, "internationalCode");
            return (Criteria) this;
        }

        public Criteria andNationalCodeIsNull() {
            addCriterion("national_code is null");
            return (Criteria) this;
        }

        public Criteria andNationalCodeIsNotNull() {
            addCriterion("national_code is not null");
            return (Criteria) this;
        }

        public Criteria andNationalCodeEqualTo(String value) {
            addCriterion("national_code =", value, "nationalCode");
            return (Criteria) this;
        }

        public Criteria andNationalCodeNotEqualTo(String value) {
            addCriterion("national_code <>", value, "nationalCode");
            return (Criteria) this;
        }

        public Criteria andNationalCodeGreaterThan(String value) {
            addCriterion("national_code >", value, "nationalCode");
            return (Criteria) this;
        }

        public Criteria andNationalCodeGreaterThanOrEqualTo(String value) {
            addCriterion("national_code >=", value, "nationalCode");
            return (Criteria) this;
        }

        public Criteria andNationalCodeLessThan(String value) {
            addCriterion("national_code <", value, "nationalCode");
            return (Criteria) this;
        }

        public Criteria andNationalCodeLessThanOrEqualTo(String value) {
            addCriterion("national_code <=", value, "nationalCode");
            return (Criteria) this;
        }

        public Criteria andNationalCodeLike(String value) {
            addCriterion("national_code like", value, "nationalCode");
            return (Criteria) this;
        }

        public Criteria andNationalCodeNotLike(String value) {
            addCriterion("national_code not like", value, "nationalCode");
            return (Criteria) this;
        }

        public Criteria andNationalCodeIn(List<String> values) {
            addCriterion("national_code in", values, "nationalCode");
            return (Criteria) this;
        }

        public Criteria andNationalCodeNotIn(List<String> values) {
            addCriterion("national_code not in", values, "nationalCode");
            return (Criteria) this;
        }

        public Criteria andNationalCodeBetween(String value1, String value2) {
            addCriterion("national_code between", value1, value2, "nationalCode");
            return (Criteria) this;
        }

        public Criteria andNationalCodeNotBetween(String value1, String value2) {
            addCriterion("national_code not between", value1, value2, "nationalCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeIsNull() {
            addCriterion("post_code is null");
            return (Criteria) this;
        }

        public Criteria andPostCodeIsNotNull() {
            addCriterion("post_code is not null");
            return (Criteria) this;
        }

        public Criteria andPostCodeEqualTo(String value) {
            addCriterion("post_code =", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeNotEqualTo(String value) {
            addCriterion("post_code <>", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeGreaterThan(String value) {
            addCriterion("post_code >", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeGreaterThanOrEqualTo(String value) {
            addCriterion("post_code >=", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeLessThan(String value) {
            addCriterion("post_code <", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeLessThanOrEqualTo(String value) {
            addCriterion("post_code <=", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeLike(String value) {
            addCriterion("post_code like", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeNotLike(String value) {
            addCriterion("post_code not like", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeIn(List<String> values) {
            addCriterion("post_code in", values, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeNotIn(List<String> values) {
            addCriterion("post_code not in", values, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeBetween(String value1, String value2) {
            addCriterion("post_code between", value1, value2, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeNotBetween(String value1, String value2) {
            addCriterion("post_code not between", value1, value2, "postCode");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(String value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(String value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(String value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(String value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(String value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(String value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLike(String value) {
            addCriterion("price like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotLike(String value) {
            addCriterion("price not like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<String> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<String> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(String value1, String value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(String value1, String value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNull() {
            addCriterion("total_price is null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNotNull() {
            addCriterion("total_price is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceEqualTo(String value) {
            addCriterion("total_price =", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotEqualTo(String value) {
            addCriterion("total_price <>", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThan(String value) {
            addCriterion("total_price >", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThanOrEqualTo(String value) {
            addCriterion("total_price >=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThan(String value) {
            addCriterion("total_price <", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThanOrEqualTo(String value) {
            addCriterion("total_price <=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLike(String value) {
            addCriterion("total_price like", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotLike(String value) {
            addCriterion("total_price not like", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIn(List<String> values) {
            addCriterion("total_price in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotIn(List<String> values) {
            addCriterion("total_price not in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceBetween(String value1, String value2) {
            addCriterion("total_price between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotBetween(String value1, String value2) {
            addCriterion("total_price not between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andCatalogIsNull() {
            addCriterion("catalog is null");
            return (Criteria) this;
        }

        public Criteria andCatalogIsNotNull() {
            addCriterion("catalog is not null");
            return (Criteria) this;
        }

        public Criteria andCatalogEqualTo(String value) {
            addCriterion("catalog =", value, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogNotEqualTo(String value) {
            addCriterion("catalog <>", value, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogGreaterThan(String value) {
            addCriterion("catalog >", value, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogGreaterThanOrEqualTo(String value) {
            addCriterion("catalog >=", value, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogLessThan(String value) {
            addCriterion("catalog <", value, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogLessThanOrEqualTo(String value) {
            addCriterion("catalog <=", value, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogLike(String value) {
            addCriterion("catalog like", value, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogNotLike(String value) {
            addCriterion("catalog not like", value, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogIn(List<String> values) {
            addCriterion("catalog in", values, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogNotIn(List<String> values) {
            addCriterion("catalog not in", values, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogBetween(String value1, String value2) {
            addCriterion("catalog between", value1, value2, "catalog");
            return (Criteria) this;
        }

        public Criteria andCatalogNotBetween(String value1, String value2) {
            addCriterion("catalog not between", value1, value2, "catalog");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ncpssd
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_ncpssd
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}