package com.gk.webmagic.demo3.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_ncpssd
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class NcpssdBeanWithBLOBs extends NcpssdBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ncpssd.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ncpssd.introduce
     *
     * @mbg.generated
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ncpssd.journal_info
     *
     * @mbg.generated
     */
    private String journalInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ncpssd.name
     *
     * @return the value of t_ncpssd.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ncpssd.name
     *
     * @param name the value for t_ncpssd.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ncpssd.introduce
     *
     * @return the value of t_ncpssd.introduce
     *
     * @mbg.generated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ncpssd.introduce
     *
     * @param introduce the value for t_ncpssd.introduce
     *
     * @mbg.generated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ncpssd.journal_info
     *
     * @return the value of t_ncpssd.journal_info
     *
     * @mbg.generated
     */
    public String getJournalInfo() {
        return journalInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ncpssd.journal_info
     *
     * @param journalInfo the value for t_ncpssd.journal_info
     *
     * @mbg.generated
     */
    public void setJournalInfo(String journalInfo) {
        this.journalInfo = journalInfo == null ? null : journalInfo.trim();
    }
}