package com.gk.webmagic.demo3.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_ncpssd
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class NcpssdBean {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ncpssd.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ncpssd.manage_department
     *
     * @mbg.generated
     */
    private String manageDepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ncpssd.sponsor_department
     *
     * @mbg.generated
     */
    private String sponsorDepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ncpssd.editor
     *
     * @mbg.generated
     */
    private String editor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ncpssd.build_time
     *
     * @mbg.generated
     */
    private String buildTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ncpssd.publish_peroid
     *
     * @mbg.generated
     */
    private String publishPeroid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ncpssd.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ncpssd.international_code
     *
     * @mbg.generated
     */
    private String internationalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ncpssd.national_code
     *
     * @mbg.generated
     */
    private String nationalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ncpssd.post_code
     *
     * @mbg.generated
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ncpssd.price
     *
     * @mbg.generated
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ncpssd.total_price
     *
     * @mbg.generated
     */
    private String totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ncpssd.catalog
     *
     * @mbg.generated
     */
    private String catalog;
    
    private String imageUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ncpssd.id
     *
     * @return the value of t_ncpssd.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ncpssd.id
     *
     * @param id the value for t_ncpssd.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ncpssd.manage_department
     *
     * @return the value of t_ncpssd.manage_department
     *
     * @mbg.generated
     */
    public String getManageDepartment() {
        return manageDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ncpssd.manage_department
     *
     * @param manageDepartment the value for t_ncpssd.manage_department
     *
     * @mbg.generated
     */
    public void setManageDepartment(String manageDepartment) {
        this.manageDepartment = manageDepartment == null ? null : manageDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ncpssd.sponsor_department
     *
     * @return the value of t_ncpssd.sponsor_department
     *
     * @mbg.generated
     */
    public String getSponsorDepartment() {
        return sponsorDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ncpssd.sponsor_department
     *
     * @param sponsorDepartment the value for t_ncpssd.sponsor_department
     *
     * @mbg.generated
     */
    public void setSponsorDepartment(String sponsorDepartment) {
        this.sponsorDepartment = sponsorDepartment == null ? null : sponsorDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ncpssd.editor
     *
     * @return the value of t_ncpssd.editor
     *
     * @mbg.generated
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ncpssd.editor
     *
     * @param editor the value for t_ncpssd.editor
     *
     * @mbg.generated
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ncpssd.build_time
     *
     * @return the value of t_ncpssd.build_time
     *
     * @mbg.generated
     */
    public String getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ncpssd.build_time
     *
     * @param buildTime the value for t_ncpssd.build_time
     *
     * @mbg.generated
     */
    public void setBuildTime(String buildTime) {
        this.buildTime = buildTime == null ? null : buildTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ncpssd.publish_peroid
     *
     * @return the value of t_ncpssd.publish_peroid
     *
     * @mbg.generated
     */
    public String getPublishPeroid() {
        return publishPeroid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ncpssd.publish_peroid
     *
     * @param publishPeroid the value for t_ncpssd.publish_peroid
     *
     * @mbg.generated
     */
    public void setPublishPeroid(String publishPeroid) {
        this.publishPeroid = publishPeroid == null ? null : publishPeroid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ncpssd.address
     *
     * @return the value of t_ncpssd.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ncpssd.address
     *
     * @param address the value for t_ncpssd.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ncpssd.international_code
     *
     * @return the value of t_ncpssd.international_code
     *
     * @mbg.generated
     */
    public String getInternationalCode() {
        return internationalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ncpssd.international_code
     *
     * @param internationalCode the value for t_ncpssd.international_code
     *
     * @mbg.generated
     */
    public void setInternationalCode(String internationalCode) {
        this.internationalCode = internationalCode == null ? null : internationalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ncpssd.national_code
     *
     * @return the value of t_ncpssd.national_code
     *
     * @mbg.generated
     */
    public String getNationalCode() {
        return nationalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ncpssd.national_code
     *
     * @param nationalCode the value for t_ncpssd.national_code
     *
     * @mbg.generated
     */
    public void setNationalCode(String nationalCode) {
        this.nationalCode = nationalCode == null ? null : nationalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ncpssd.post_code
     *
     * @return the value of t_ncpssd.post_code
     *
     * @mbg.generated
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ncpssd.post_code
     *
     * @param postCode the value for t_ncpssd.post_code
     *
     * @mbg.generated
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ncpssd.price
     *
     * @return the value of t_ncpssd.price
     *
     * @mbg.generated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ncpssd.price
     *
     * @param price the value for t_ncpssd.price
     *
     * @mbg.generated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ncpssd.total_price
     *
     * @return the value of t_ncpssd.total_price
     *
     * @mbg.generated
     */
    public String getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ncpssd.total_price
     *
     * @param totalPrice the value for t_ncpssd.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(String totalPrice) {
        this.totalPrice = totalPrice == null ? null : totalPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ncpssd.catalog
     *
     * @return the value of t_ncpssd.catalog
     *
     * @mbg.generated
     */
    public String getCatalog() {
        return catalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ncpssd.catalog
     *
     * @param catalog the value for t_ncpssd.catalog
     *
     * @mbg.generated
     */
    public void setCatalog(String catalog) {
        this.catalog = catalog == null ? null : catalog.trim();
    }

	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}
}