package com.gk.webmagic.demo2.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table down_periodical_wanfang
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class DownPeriodicalWanfang {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   期刊id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.DOC_ID
     *
     * @mbg.generated
     */
    private String docId;

    /**
     * Database Column Remarks:
     *   期刊收登标识号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.PERI_VOL_ID
     *
     * @mbg.generated
     */
    private Integer periVolId;

    /**
     * Database Column Remarks:
     *   DOI
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.DOI
     *
     * @mbg.generated
     */
    private String doi;

    /**
     * Database Column Remarks:
     *   收录来源 spider site id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.SITE_ID
     *
     * @mbg.generated
     */
    private Integer siteId;

    /**
     * Database Column Remarks:
     *   站内内部编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.CALL_NUM
     *
     * @mbg.generated
     */
    private String callNum;

    /**
     * Database Column Remarks:
     *   题录类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.DOC_TYPE_CODE
     *
     * @mbg.generated
     */
    private Integer docTypeCode;

    /**
     * Database Column Remarks:
     *   国别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.COUNTRY_CODE
     *
     * @mbg.generated
     */
    private String countryCode;

    /**
     * Database Column Remarks:
     *   语言
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.LANG_CODE
     *
     * @mbg.generated
     */
    private String langCode;

    /**
     * Database Column Remarks:
     *   文章标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   文章译名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.TRANS_TITLE
     *
     * @mbg.generated
     */
    private String transTitle;

    /**
     * Database Column Remarks:
     *   简短标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.SHORT_NAME
     *
     * @mbg.generated
     */
    private String shortName;

    /**
     * Database Column Remarks:
     *   作者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.AUTHOR
     *
     * @mbg.generated
     */
    private String author;

    /**
     * Database Column Remarks:
     *   作者译名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.TRANS_AUTHOR
     *
     * @mbg.generated
     */
    private String transAuthor;

    /**
     * Database Column Remarks:
     *   作者机构
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.INSTITUTION
     *
     * @mbg.generated
     */
    private String institution;

    /**
     * Database Column Remarks:
     *   作者地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.ADDRESS
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   年份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.PUB_YEAR
     *
     * @mbg.generated
     */
    private String pubYear;

    /**
     * Database Column Remarks:
     *   页码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.PAGE_NUM
     *
     * @mbg.generated
     */
    private String pageNum;

    /**
     * Database Column Remarks:
     *   关键词
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.KEYWORDS
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     * Database Column Remarks:
     *   学科分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.COURSE_CLASS
     *
     * @mbg.generated
     */
    private String courseClass;

    /**
     * Database Column Remarks:
     *   分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.CLASS_NO
     *
     * @mbg.generated
     */
    private String classNo;

    /**
     * Database Column Remarks:
     *   标签
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.TITLE_TAG
     *
     * @mbg.generated
     */
    private String titleTag;

    /**
     * Database Column Remarks:
     *   数据库提供者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.DATA_SOURCE
     *
     * @mbg.generated
     */
    private String dataSource;

    /**
     * Database Column Remarks:
     *   链接地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.URL
     *
     * @mbg.generated
     */
    private String url;

    /**
     * Database Column Remarks:
     *   字数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.WORD_COUNT
     *
     * @mbg.generated
     */
    private Integer wordCount;

    /**
     * Database Column Remarks:
     *   发表日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.PUB_DATE
     *
     * @mbg.generated
     */
    private String pubDate;

    /**
     * Database Column Remarks:
     *   文章类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.TITIE_TPYE
     *
     * @mbg.generated
     */
    private String titieTpye;

    /**
     * Database Column Remarks:
     *   获取号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.GET_CODE
     *
     * @mbg.generated
     */
    private String getCode;

    /**
     * Database Column Remarks:
     *   BibTeX关键字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.BIBTEX
     *
     * @mbg.generated
     */
    private String bibtex;

    /**
     * Database Column Remarks:
     *   主题词
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.SUBJECT_TERMS
     *
     * @mbg.generated
     */
    private String subjectTerms;

    /**
     * Database Column Remarks:
     *   主题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.SUBJECT
     *
     * @mbg.generated
     */
    private String subject;

    /**
     * Database Column Remarks:
     *   影响因子1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.IMPACT_FACTOR1
     *
     * @mbg.generated
     */
    private String impactFactor1;

    /**
     * Database Column Remarks:
     *   影响因子2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.IMPACT_FACTOR2
     *
     * @mbg.generated
     */
    private String impactFactor2;

    /**
     * Database Column Remarks:
     *   收录范围
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.CITATION_INDEX
     *
     * @mbg.generated
     */
    private String citationIndex;

    /**
     * Database Column Remarks:
     *   被引用次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.TIMES_CITED
     *
     * @mbg.generated
     */
    private Integer timesCited;

    /**
     * Database Column Remarks:
     *   引用参考文献数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.REFER_NUM
     *
     * @mbg.generated
     */
    private Integer referNum;

    /**
     * Database Column Remarks:
     *   全文链接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.FULLTEXT_LINK
     *
     * @mbg.generated
     */
    private String fulltextLink;

    /**
     * Database Column Remarks:
     *   总下载量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.TOTAL_DOWN
     *
     * @mbg.generated
     */
    private Integer totalDown;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_periodical_wanfang.ADD_TIME
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.ID
     *
     * @return the value of down_periodical_wanfang.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.ID
     *
     * @param id the value for down_periodical_wanfang.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.DOC_ID
     *
     * @return the value of down_periodical_wanfang.DOC_ID
     *
     * @mbg.generated
     */
    public String getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.DOC_ID
     *
     * @param docId the value for down_periodical_wanfang.DOC_ID
     *
     * @mbg.generated
     */
    public void setDocId(String docId) {
        this.docId = docId == null ? null : docId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.PERI_VOL_ID
     *
     * @return the value of down_periodical_wanfang.PERI_VOL_ID
     *
     * @mbg.generated
     */
    public Integer getPeriVolId() {
        return periVolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.PERI_VOL_ID
     *
     * @param periVolId the value for down_periodical_wanfang.PERI_VOL_ID
     *
     * @mbg.generated
     */
    public void setPeriVolId(Integer periVolId) {
        this.periVolId = periVolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.DOI
     *
     * @return the value of down_periodical_wanfang.DOI
     *
     * @mbg.generated
     */
    public String getDoi() {
        return doi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.DOI
     *
     * @param doi the value for down_periodical_wanfang.DOI
     *
     * @mbg.generated
     */
    public void setDoi(String doi) {
        this.doi = doi == null ? null : doi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.SITE_ID
     *
     * @return the value of down_periodical_wanfang.SITE_ID
     *
     * @mbg.generated
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.SITE_ID
     *
     * @param siteId the value for down_periodical_wanfang.SITE_ID
     *
     * @mbg.generated
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.CALL_NUM
     *
     * @return the value of down_periodical_wanfang.CALL_NUM
     *
     * @mbg.generated
     */
    public String getCallNum() {
        return callNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.CALL_NUM
     *
     * @param callNum the value for down_periodical_wanfang.CALL_NUM
     *
     * @mbg.generated
     */
    public void setCallNum(String callNum) {
        this.callNum = callNum == null ? null : callNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.DOC_TYPE_CODE
     *
     * @return the value of down_periodical_wanfang.DOC_TYPE_CODE
     *
     * @mbg.generated
     */
    public Integer getDocTypeCode() {
        return docTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.DOC_TYPE_CODE
     *
     * @param docTypeCode the value for down_periodical_wanfang.DOC_TYPE_CODE
     *
     * @mbg.generated
     */
    public void setDocTypeCode(Integer docTypeCode) {
        this.docTypeCode = docTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.COUNTRY_CODE
     *
     * @return the value of down_periodical_wanfang.COUNTRY_CODE
     *
     * @mbg.generated
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.COUNTRY_CODE
     *
     * @param countryCode the value for down_periodical_wanfang.COUNTRY_CODE
     *
     * @mbg.generated
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.LANG_CODE
     *
     * @return the value of down_periodical_wanfang.LANG_CODE
     *
     * @mbg.generated
     */
    public String getLangCode() {
        return langCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.LANG_CODE
     *
     * @param langCode the value for down_periodical_wanfang.LANG_CODE
     *
     * @mbg.generated
     */
    public void setLangCode(String langCode) {
        this.langCode = langCode == null ? null : langCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.TITLE
     *
     * @return the value of down_periodical_wanfang.TITLE
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.TITLE
     *
     * @param title the value for down_periodical_wanfang.TITLE
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.TRANS_TITLE
     *
     * @return the value of down_periodical_wanfang.TRANS_TITLE
     *
     * @mbg.generated
     */
    public String getTransTitle() {
        return transTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.TRANS_TITLE
     *
     * @param transTitle the value for down_periodical_wanfang.TRANS_TITLE
     *
     * @mbg.generated
     */
    public void setTransTitle(String transTitle) {
        this.transTitle = transTitle == null ? null : transTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.SHORT_NAME
     *
     * @return the value of down_periodical_wanfang.SHORT_NAME
     *
     * @mbg.generated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.SHORT_NAME
     *
     * @param shortName the value for down_periodical_wanfang.SHORT_NAME
     *
     * @mbg.generated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.AUTHOR
     *
     * @return the value of down_periodical_wanfang.AUTHOR
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.AUTHOR
     *
     * @param author the value for down_periodical_wanfang.AUTHOR
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.TRANS_AUTHOR
     *
     * @return the value of down_periodical_wanfang.TRANS_AUTHOR
     *
     * @mbg.generated
     */
    public String getTransAuthor() {
        return transAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.TRANS_AUTHOR
     *
     * @param transAuthor the value for down_periodical_wanfang.TRANS_AUTHOR
     *
     * @mbg.generated
     */
    public void setTransAuthor(String transAuthor) {
        this.transAuthor = transAuthor == null ? null : transAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.INSTITUTION
     *
     * @return the value of down_periodical_wanfang.INSTITUTION
     *
     * @mbg.generated
     */
    public String getInstitution() {
        return institution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.INSTITUTION
     *
     * @param institution the value for down_periodical_wanfang.INSTITUTION
     *
     * @mbg.generated
     */
    public void setInstitution(String institution) {
        this.institution = institution == null ? null : institution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.ADDRESS
     *
     * @return the value of down_periodical_wanfang.ADDRESS
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.ADDRESS
     *
     * @param address the value for down_periodical_wanfang.ADDRESS
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.PUB_YEAR
     *
     * @return the value of down_periodical_wanfang.PUB_YEAR
     *
     * @mbg.generated
     */
    public String getPubYear() {
        return pubYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.PUB_YEAR
     *
     * @param pubYear the value for down_periodical_wanfang.PUB_YEAR
     *
     * @mbg.generated
     */
    public void setPubYear(String pubYear) {
        this.pubYear = pubYear == null ? null : pubYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.PAGE_NUM
     *
     * @return the value of down_periodical_wanfang.PAGE_NUM
     *
     * @mbg.generated
     */
    public String getPageNum() {
        return pageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.PAGE_NUM
     *
     * @param pageNum the value for down_periodical_wanfang.PAGE_NUM
     *
     * @mbg.generated
     */
    public void setPageNum(String pageNum) {
        this.pageNum = pageNum == null ? null : pageNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.KEYWORDS
     *
     * @return the value of down_periodical_wanfang.KEYWORDS
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.KEYWORDS
     *
     * @param keywords the value for down_periodical_wanfang.KEYWORDS
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.COURSE_CLASS
     *
     * @return the value of down_periodical_wanfang.COURSE_CLASS
     *
     * @mbg.generated
     */
    public String getCourseClass() {
        return courseClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.COURSE_CLASS
     *
     * @param courseClass the value for down_periodical_wanfang.COURSE_CLASS
     *
     * @mbg.generated
     */
    public void setCourseClass(String courseClass) {
        this.courseClass = courseClass == null ? null : courseClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.CLASS_NO
     *
     * @return the value of down_periodical_wanfang.CLASS_NO
     *
     * @mbg.generated
     */
    public String getClassNo() {
        return classNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.CLASS_NO
     *
     * @param classNo the value for down_periodical_wanfang.CLASS_NO
     *
     * @mbg.generated
     */
    public void setClassNo(String classNo) {
        this.classNo = classNo == null ? null : classNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.TITLE_TAG
     *
     * @return the value of down_periodical_wanfang.TITLE_TAG
     *
     * @mbg.generated
     */
    public String getTitleTag() {
        return titleTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.TITLE_TAG
     *
     * @param titleTag the value for down_periodical_wanfang.TITLE_TAG
     *
     * @mbg.generated
     */
    public void setTitleTag(String titleTag) {
        this.titleTag = titleTag == null ? null : titleTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.DATA_SOURCE
     *
     * @return the value of down_periodical_wanfang.DATA_SOURCE
     *
     * @mbg.generated
     */
    public String getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.DATA_SOURCE
     *
     * @param dataSource the value for down_periodical_wanfang.DATA_SOURCE
     *
     * @mbg.generated
     */
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource == null ? null : dataSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.URL
     *
     * @return the value of down_periodical_wanfang.URL
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.URL
     *
     * @param url the value for down_periodical_wanfang.URL
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.WORD_COUNT
     *
     * @return the value of down_periodical_wanfang.WORD_COUNT
     *
     * @mbg.generated
     */
    public Integer getWordCount() {
        return wordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.WORD_COUNT
     *
     * @param wordCount the value for down_periodical_wanfang.WORD_COUNT
     *
     * @mbg.generated
     */
    public void setWordCount(Integer wordCount) {
        this.wordCount = wordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.PUB_DATE
     *
     * @return the value of down_periodical_wanfang.PUB_DATE
     *
     * @mbg.generated
     */
    public String getPubDate() {
        return pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.PUB_DATE
     *
     * @param pubDate the value for down_periodical_wanfang.PUB_DATE
     *
     * @mbg.generated
     */
    public void setPubDate(String pubDate) {
        this.pubDate = pubDate == null ? null : pubDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.TITIE_TPYE
     *
     * @return the value of down_periodical_wanfang.TITIE_TPYE
     *
     * @mbg.generated
     */
    public String getTitieTpye() {
        return titieTpye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.TITIE_TPYE
     *
     * @param titieTpye the value for down_periodical_wanfang.TITIE_TPYE
     *
     * @mbg.generated
     */
    public void setTitieTpye(String titieTpye) {
        this.titieTpye = titieTpye == null ? null : titieTpye.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.GET_CODE
     *
     * @return the value of down_periodical_wanfang.GET_CODE
     *
     * @mbg.generated
     */
    public String getGetCode() {
        return getCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.GET_CODE
     *
     * @param getCode the value for down_periodical_wanfang.GET_CODE
     *
     * @mbg.generated
     */
    public void setGetCode(String getCode) {
        this.getCode = getCode == null ? null : getCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.BIBTEX
     *
     * @return the value of down_periodical_wanfang.BIBTEX
     *
     * @mbg.generated
     */
    public String getBibtex() {
        return bibtex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.BIBTEX
     *
     * @param bibtex the value for down_periodical_wanfang.BIBTEX
     *
     * @mbg.generated
     */
    public void setBibtex(String bibtex) {
        this.bibtex = bibtex == null ? null : bibtex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.SUBJECT_TERMS
     *
     * @return the value of down_periodical_wanfang.SUBJECT_TERMS
     *
     * @mbg.generated
     */
    public String getSubjectTerms() {
        return subjectTerms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.SUBJECT_TERMS
     *
     * @param subjectTerms the value for down_periodical_wanfang.SUBJECT_TERMS
     *
     * @mbg.generated
     */
    public void setSubjectTerms(String subjectTerms) {
        this.subjectTerms = subjectTerms == null ? null : subjectTerms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.SUBJECT
     *
     * @return the value of down_periodical_wanfang.SUBJECT
     *
     * @mbg.generated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.SUBJECT
     *
     * @param subject the value for down_periodical_wanfang.SUBJECT
     *
     * @mbg.generated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.IMPACT_FACTOR1
     *
     * @return the value of down_periodical_wanfang.IMPACT_FACTOR1
     *
     * @mbg.generated
     */
    public String getImpactFactor1() {
        return impactFactor1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.IMPACT_FACTOR1
     *
     * @param impactFactor1 the value for down_periodical_wanfang.IMPACT_FACTOR1
     *
     * @mbg.generated
     */
    public void setImpactFactor1(String impactFactor1) {
        this.impactFactor1 = impactFactor1 == null ? null : impactFactor1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.IMPACT_FACTOR2
     *
     * @return the value of down_periodical_wanfang.IMPACT_FACTOR2
     *
     * @mbg.generated
     */
    public String getImpactFactor2() {
        return impactFactor2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.IMPACT_FACTOR2
     *
     * @param impactFactor2 the value for down_periodical_wanfang.IMPACT_FACTOR2
     *
     * @mbg.generated
     */
    public void setImpactFactor2(String impactFactor2) {
        this.impactFactor2 = impactFactor2 == null ? null : impactFactor2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.CITATION_INDEX
     *
     * @return the value of down_periodical_wanfang.CITATION_INDEX
     *
     * @mbg.generated
     */
    public String getCitationIndex() {
        return citationIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.CITATION_INDEX
     *
     * @param citationIndex the value for down_periodical_wanfang.CITATION_INDEX
     *
     * @mbg.generated
     */
    public void setCitationIndex(String citationIndex) {
        this.citationIndex = citationIndex == null ? null : citationIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.TIMES_CITED
     *
     * @return the value of down_periodical_wanfang.TIMES_CITED
     *
     * @mbg.generated
     */
    public Integer getTimesCited() {
        return timesCited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.TIMES_CITED
     *
     * @param timesCited the value for down_periodical_wanfang.TIMES_CITED
     *
     * @mbg.generated
     */
    public void setTimesCited(Integer timesCited) {
        this.timesCited = timesCited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.REFER_NUM
     *
     * @return the value of down_periodical_wanfang.REFER_NUM
     *
     * @mbg.generated
     */
    public Integer getReferNum() {
        return referNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.REFER_NUM
     *
     * @param referNum the value for down_periodical_wanfang.REFER_NUM
     *
     * @mbg.generated
     */
    public void setReferNum(Integer referNum) {
        this.referNum = referNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.FULLTEXT_LINK
     *
     * @return the value of down_periodical_wanfang.FULLTEXT_LINK
     *
     * @mbg.generated
     */
    public String getFulltextLink() {
        return fulltextLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.FULLTEXT_LINK
     *
     * @param fulltextLink the value for down_periodical_wanfang.FULLTEXT_LINK
     *
     * @mbg.generated
     */
    public void setFulltextLink(String fulltextLink) {
        this.fulltextLink = fulltextLink == null ? null : fulltextLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.TOTAL_DOWN
     *
     * @return the value of down_periodical_wanfang.TOTAL_DOWN
     *
     * @mbg.generated
     */
    public Integer getTotalDown() {
        return totalDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.TOTAL_DOWN
     *
     * @param totalDown the value for down_periodical_wanfang.TOTAL_DOWN
     *
     * @mbg.generated
     */
    public void setTotalDown(Integer totalDown) {
        this.totalDown = totalDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_periodical_wanfang.ADD_TIME
     *
     * @return the value of down_periodical_wanfang.ADD_TIME
     *
     * @mbg.generated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_periodical_wanfang.ADD_TIME
     *
     * @param addTime the value for down_periodical_wanfang.ADD_TIME
     *
     * @mbg.generated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}