package com.gk.webmagic.demo2.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DownPeriVolLstExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table down_peri_vol_lst
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table down_peri_vol_lst
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table down_peri_vol_lst
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_peri_vol_lst
     *
     * @mbg.generated
     */
    public DownPeriVolLstExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_peri_vol_lst
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_peri_vol_lst
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_peri_vol_lst
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_peri_vol_lst
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_peri_vol_lst
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_peri_vol_lst
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_peri_vol_lst
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_peri_vol_lst
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_peri_vol_lst
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_peri_vol_lst
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table down_peri_vol_lst
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPeriVolIdIsNull() {
            addCriterion("PERI_VOL_ID is null");
            return (Criteria) this;
        }

        public Criteria andPeriVolIdIsNotNull() {
            addCriterion("PERI_VOL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPeriVolIdEqualTo(Integer value) {
            addCriterion("PERI_VOL_ID =", value, "periVolId");
            return (Criteria) this;
        }

        public Criteria andPeriVolIdNotEqualTo(Integer value) {
            addCriterion("PERI_VOL_ID <>", value, "periVolId");
            return (Criteria) this;
        }

        public Criteria andPeriVolIdGreaterThan(Integer value) {
            addCriterion("PERI_VOL_ID >", value, "periVolId");
            return (Criteria) this;
        }

        public Criteria andPeriVolIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PERI_VOL_ID >=", value, "periVolId");
            return (Criteria) this;
        }

        public Criteria andPeriVolIdLessThan(Integer value) {
            addCriterion("PERI_VOL_ID <", value, "periVolId");
            return (Criteria) this;
        }

        public Criteria andPeriVolIdLessThanOrEqualTo(Integer value) {
            addCriterion("PERI_VOL_ID <=", value, "periVolId");
            return (Criteria) this;
        }

        public Criteria andPeriVolIdIn(List<Integer> values) {
            addCriterion("PERI_VOL_ID in", values, "periVolId");
            return (Criteria) this;
        }

        public Criteria andPeriVolIdNotIn(List<Integer> values) {
            addCriterion("PERI_VOL_ID not in", values, "periVolId");
            return (Criteria) this;
        }

        public Criteria andPeriVolIdBetween(Integer value1, Integer value2) {
            addCriterion("PERI_VOL_ID between", value1, value2, "periVolId");
            return (Criteria) this;
        }

        public Criteria andPeriVolIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PERI_VOL_ID not between", value1, value2, "periVolId");
            return (Criteria) this;
        }

        public Criteria andDocIdIsNull() {
            addCriterion("DOC_ID is null");
            return (Criteria) this;
        }

        public Criteria andDocIdIsNotNull() {
            addCriterion("DOC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDocIdEqualTo(String value) {
            addCriterion("DOC_ID =", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdNotEqualTo(String value) {
            addCriterion("DOC_ID <>", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdGreaterThan(String value) {
            addCriterion("DOC_ID >", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdGreaterThanOrEqualTo(String value) {
            addCriterion("DOC_ID >=", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdLessThan(String value) {
            addCriterion("DOC_ID <", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdLessThanOrEqualTo(String value) {
            addCriterion("DOC_ID <=", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdLike(String value) {
            addCriterion("DOC_ID like", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdNotLike(String value) {
            addCriterion("DOC_ID not like", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdIn(List<String> values) {
            addCriterion("DOC_ID in", values, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdNotIn(List<String> values) {
            addCriterion("DOC_ID not in", values, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdBetween(String value1, String value2) {
            addCriterion("DOC_ID between", value1, value2, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdNotBetween(String value1, String value2) {
            addCriterion("DOC_ID not between", value1, value2, "docId");
            return (Criteria) this;
        }

        public Criteria andBookSizeCodeIsNull() {
            addCriterion("BOOK_SIZE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andBookSizeCodeIsNotNull() {
            addCriterion("BOOK_SIZE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andBookSizeCodeEqualTo(Integer value) {
            addCriterion("BOOK_SIZE_CODE =", value, "bookSizeCode");
            return (Criteria) this;
        }

        public Criteria andBookSizeCodeNotEqualTo(Integer value) {
            addCriterion("BOOK_SIZE_CODE <>", value, "bookSizeCode");
            return (Criteria) this;
        }

        public Criteria andBookSizeCodeGreaterThan(Integer value) {
            addCriterion("BOOK_SIZE_CODE >", value, "bookSizeCode");
            return (Criteria) this;
        }

        public Criteria andBookSizeCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("BOOK_SIZE_CODE >=", value, "bookSizeCode");
            return (Criteria) this;
        }

        public Criteria andBookSizeCodeLessThan(Integer value) {
            addCriterion("BOOK_SIZE_CODE <", value, "bookSizeCode");
            return (Criteria) this;
        }

        public Criteria andBookSizeCodeLessThanOrEqualTo(Integer value) {
            addCriterion("BOOK_SIZE_CODE <=", value, "bookSizeCode");
            return (Criteria) this;
        }

        public Criteria andBookSizeCodeIn(List<Integer> values) {
            addCriterion("BOOK_SIZE_CODE in", values, "bookSizeCode");
            return (Criteria) this;
        }

        public Criteria andBookSizeCodeNotIn(List<Integer> values) {
            addCriterion("BOOK_SIZE_CODE not in", values, "bookSizeCode");
            return (Criteria) this;
        }

        public Criteria andBookSizeCodeBetween(Integer value1, Integer value2) {
            addCriterion("BOOK_SIZE_CODE between", value1, value2, "bookSizeCode");
            return (Criteria) this;
        }

        public Criteria andBookSizeCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("BOOK_SIZE_CODE not between", value1, value2, "bookSizeCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIsNull() {
            addCriterion("CURRENCY_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIsNotNull() {
            addCriterion("CURRENCY_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeEqualTo(Integer value) {
            addCriterion("CURRENCY_CODE =", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotEqualTo(Integer value) {
            addCriterion("CURRENCY_CODE <>", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeGreaterThan(Integer value) {
            addCriterion("CURRENCY_CODE >", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("CURRENCY_CODE >=", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeLessThan(Integer value) {
            addCriterion("CURRENCY_CODE <", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeLessThanOrEqualTo(Integer value) {
            addCriterion("CURRENCY_CODE <=", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIn(List<Integer> values) {
            addCriterion("CURRENCY_CODE in", values, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotIn(List<Integer> values) {
            addCriterion("CURRENCY_CODE not in", values, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeBetween(Integer value1, Integer value2) {
            addCriterion("CURRENCY_CODE between", value1, value2, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("CURRENCY_CODE not between", value1, value2, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeIsNull() {
            addCriterion("CARRIER_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeIsNotNull() {
            addCriterion("CARRIER_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeEqualTo(String value) {
            addCriterion("CARRIER_CODE =", value, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeNotEqualTo(String value) {
            addCriterion("CARRIER_CODE <>", value, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeGreaterThan(String value) {
            addCriterion("CARRIER_CODE >", value, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CARRIER_CODE >=", value, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeLessThan(String value) {
            addCriterion("CARRIER_CODE <", value, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeLessThanOrEqualTo(String value) {
            addCriterion("CARRIER_CODE <=", value, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeLike(String value) {
            addCriterion("CARRIER_CODE like", value, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeNotLike(String value) {
            addCriterion("CARRIER_CODE not like", value, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeIn(List<String> values) {
            addCriterion("CARRIER_CODE in", values, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeNotIn(List<String> values) {
            addCriterion("CARRIER_CODE not in", values, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeBetween(String value1, String value2) {
            addCriterion("CARRIER_CODE between", value1, value2, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeNotBetween(String value1, String value2) {
            addCriterion("CARRIER_CODE not between", value1, value2, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCoverVolIsNull() {
            addCriterion("COVER_VOL is null");
            return (Criteria) this;
        }

        public Criteria andCoverVolIsNotNull() {
            addCriterion("COVER_VOL is not null");
            return (Criteria) this;
        }

        public Criteria andCoverVolEqualTo(String value) {
            addCriterion("COVER_VOL =", value, "coverVol");
            return (Criteria) this;
        }

        public Criteria andCoverVolNotEqualTo(String value) {
            addCriterion("COVER_VOL <>", value, "coverVol");
            return (Criteria) this;
        }

        public Criteria andCoverVolGreaterThan(String value) {
            addCriterion("COVER_VOL >", value, "coverVol");
            return (Criteria) this;
        }

        public Criteria andCoverVolGreaterThanOrEqualTo(String value) {
            addCriterion("COVER_VOL >=", value, "coverVol");
            return (Criteria) this;
        }

        public Criteria andCoverVolLessThan(String value) {
            addCriterion("COVER_VOL <", value, "coverVol");
            return (Criteria) this;
        }

        public Criteria andCoverVolLessThanOrEqualTo(String value) {
            addCriterion("COVER_VOL <=", value, "coverVol");
            return (Criteria) this;
        }

        public Criteria andCoverVolLike(String value) {
            addCriterion("COVER_VOL like", value, "coverVol");
            return (Criteria) this;
        }

        public Criteria andCoverVolNotLike(String value) {
            addCriterion("COVER_VOL not like", value, "coverVol");
            return (Criteria) this;
        }

        public Criteria andCoverVolIn(List<String> values) {
            addCriterion("COVER_VOL in", values, "coverVol");
            return (Criteria) this;
        }

        public Criteria andCoverVolNotIn(List<String> values) {
            addCriterion("COVER_VOL not in", values, "coverVol");
            return (Criteria) this;
        }

        public Criteria andCoverVolBetween(String value1, String value2) {
            addCriterion("COVER_VOL between", value1, value2, "coverVol");
            return (Criteria) this;
        }

        public Criteria andCoverVolNotBetween(String value1, String value2) {
            addCriterion("COVER_VOL not between", value1, value2, "coverVol");
            return (Criteria) this;
        }

        public Criteria andCoverIssueIsNull() {
            addCriterion("COVER_ISSUE is null");
            return (Criteria) this;
        }

        public Criteria andCoverIssueIsNotNull() {
            addCriterion("COVER_ISSUE is not null");
            return (Criteria) this;
        }

        public Criteria andCoverIssueEqualTo(String value) {
            addCriterion("COVER_ISSUE =", value, "coverIssue");
            return (Criteria) this;
        }

        public Criteria andCoverIssueNotEqualTo(String value) {
            addCriterion("COVER_ISSUE <>", value, "coverIssue");
            return (Criteria) this;
        }

        public Criteria andCoverIssueGreaterThan(String value) {
            addCriterion("COVER_ISSUE >", value, "coverIssue");
            return (Criteria) this;
        }

        public Criteria andCoverIssueGreaterThanOrEqualTo(String value) {
            addCriterion("COVER_ISSUE >=", value, "coverIssue");
            return (Criteria) this;
        }

        public Criteria andCoverIssueLessThan(String value) {
            addCriterion("COVER_ISSUE <", value, "coverIssue");
            return (Criteria) this;
        }

        public Criteria andCoverIssueLessThanOrEqualTo(String value) {
            addCriterion("COVER_ISSUE <=", value, "coverIssue");
            return (Criteria) this;
        }

        public Criteria andCoverIssueLike(String value) {
            addCriterion("COVER_ISSUE like", value, "coverIssue");
            return (Criteria) this;
        }

        public Criteria andCoverIssueNotLike(String value) {
            addCriterion("COVER_ISSUE not like", value, "coverIssue");
            return (Criteria) this;
        }

        public Criteria andCoverIssueIn(List<String> values) {
            addCriterion("COVER_ISSUE in", values, "coverIssue");
            return (Criteria) this;
        }

        public Criteria andCoverIssueNotIn(List<String> values) {
            addCriterion("COVER_ISSUE not in", values, "coverIssue");
            return (Criteria) this;
        }

        public Criteria andCoverIssueBetween(String value1, String value2) {
            addCriterion("COVER_ISSUE between", value1, value2, "coverIssue");
            return (Criteria) this;
        }

        public Criteria andCoverIssueNotBetween(String value1, String value2) {
            addCriterion("COVER_ISSUE not between", value1, value2, "coverIssue");
            return (Criteria) this;
        }

        public Criteria andCoverIssueTotalIsNull() {
            addCriterion("COVER_ISSUE_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andCoverIssueTotalIsNotNull() {
            addCriterion("COVER_ISSUE_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andCoverIssueTotalEqualTo(String value) {
            addCriterion("COVER_ISSUE_TOTAL =", value, "coverIssueTotal");
            return (Criteria) this;
        }

        public Criteria andCoverIssueTotalNotEqualTo(String value) {
            addCriterion("COVER_ISSUE_TOTAL <>", value, "coverIssueTotal");
            return (Criteria) this;
        }

        public Criteria andCoverIssueTotalGreaterThan(String value) {
            addCriterion("COVER_ISSUE_TOTAL >", value, "coverIssueTotal");
            return (Criteria) this;
        }

        public Criteria andCoverIssueTotalGreaterThanOrEqualTo(String value) {
            addCriterion("COVER_ISSUE_TOTAL >=", value, "coverIssueTotal");
            return (Criteria) this;
        }

        public Criteria andCoverIssueTotalLessThan(String value) {
            addCriterion("COVER_ISSUE_TOTAL <", value, "coverIssueTotal");
            return (Criteria) this;
        }

        public Criteria andCoverIssueTotalLessThanOrEqualTo(String value) {
            addCriterion("COVER_ISSUE_TOTAL <=", value, "coverIssueTotal");
            return (Criteria) this;
        }

        public Criteria andCoverIssueTotalLike(String value) {
            addCriterion("COVER_ISSUE_TOTAL like", value, "coverIssueTotal");
            return (Criteria) this;
        }

        public Criteria andCoverIssueTotalNotLike(String value) {
            addCriterion("COVER_ISSUE_TOTAL not like", value, "coverIssueTotal");
            return (Criteria) this;
        }

        public Criteria andCoverIssueTotalIn(List<String> values) {
            addCriterion("COVER_ISSUE_TOTAL in", values, "coverIssueTotal");
            return (Criteria) this;
        }

        public Criteria andCoverIssueTotalNotIn(List<String> values) {
            addCriterion("COVER_ISSUE_TOTAL not in", values, "coverIssueTotal");
            return (Criteria) this;
        }

        public Criteria andCoverIssueTotalBetween(String value1, String value2) {
            addCriterion("COVER_ISSUE_TOTAL between", value1, value2, "coverIssueTotal");
            return (Criteria) this;
        }

        public Criteria andCoverIssueTotalNotBetween(String value1, String value2) {
            addCriterion("COVER_ISSUE_TOTAL not between", value1, value2, "coverIssueTotal");
            return (Criteria) this;
        }

        public Criteria andExpectDateIsNull() {
            addCriterion("EXPECT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andExpectDateIsNotNull() {
            addCriterion("EXPECT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andExpectDateEqualTo(Date value) {
            addCriterion("EXPECT_DATE =", value, "expectDate");
            return (Criteria) this;
        }

        public Criteria andExpectDateNotEqualTo(Date value) {
            addCriterion("EXPECT_DATE <>", value, "expectDate");
            return (Criteria) this;
        }

        public Criteria andExpectDateGreaterThan(Date value) {
            addCriterion("EXPECT_DATE >", value, "expectDate");
            return (Criteria) this;
        }

        public Criteria andExpectDateGreaterThanOrEqualTo(Date value) {
            addCriterion("EXPECT_DATE >=", value, "expectDate");
            return (Criteria) this;
        }

        public Criteria andExpectDateLessThan(Date value) {
            addCriterion("EXPECT_DATE <", value, "expectDate");
            return (Criteria) this;
        }

        public Criteria andExpectDateLessThanOrEqualTo(Date value) {
            addCriterion("EXPECT_DATE <=", value, "expectDate");
            return (Criteria) this;
        }

        public Criteria andExpectDateIn(List<Date> values) {
            addCriterion("EXPECT_DATE in", values, "expectDate");
            return (Criteria) this;
        }

        public Criteria andExpectDateNotIn(List<Date> values) {
            addCriterion("EXPECT_DATE not in", values, "expectDate");
            return (Criteria) this;
        }

        public Criteria andExpectDateBetween(Date value1, Date value2) {
            addCriterion("EXPECT_DATE between", value1, value2, "expectDate");
            return (Criteria) this;
        }

        public Criteria andExpectDateNotBetween(Date value1, Date value2) {
            addCriterion("EXPECT_DATE not between", value1, value2, "expectDate");
            return (Criteria) this;
        }

        public Criteria andPublYearIsNull() {
            addCriterion("PUBL_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andPublYearIsNotNull() {
            addCriterion("PUBL_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andPublYearEqualTo(String value) {
            addCriterion("PUBL_YEAR =", value, "publYear");
            return (Criteria) this;
        }

        public Criteria andPublYearNotEqualTo(String value) {
            addCriterion("PUBL_YEAR <>", value, "publYear");
            return (Criteria) this;
        }

        public Criteria andPublYearGreaterThan(String value) {
            addCriterion("PUBL_YEAR >", value, "publYear");
            return (Criteria) this;
        }

        public Criteria andPublYearGreaterThanOrEqualTo(String value) {
            addCriterion("PUBL_YEAR >=", value, "publYear");
            return (Criteria) this;
        }

        public Criteria andPublYearLessThan(String value) {
            addCriterion("PUBL_YEAR <", value, "publYear");
            return (Criteria) this;
        }

        public Criteria andPublYearLessThanOrEqualTo(String value) {
            addCriterion("PUBL_YEAR <=", value, "publYear");
            return (Criteria) this;
        }

        public Criteria andPublYearLike(String value) {
            addCriterion("PUBL_YEAR like", value, "publYear");
            return (Criteria) this;
        }

        public Criteria andPublYearNotLike(String value) {
            addCriterion("PUBL_YEAR not like", value, "publYear");
            return (Criteria) this;
        }

        public Criteria andPublYearIn(List<String> values) {
            addCriterion("PUBL_YEAR in", values, "publYear");
            return (Criteria) this;
        }

        public Criteria andPublYearNotIn(List<String> values) {
            addCriterion("PUBL_YEAR not in", values, "publYear");
            return (Criteria) this;
        }

        public Criteria andPublYearBetween(String value1, String value2) {
            addCriterion("PUBL_YEAR between", value1, value2, "publYear");
            return (Criteria) this;
        }

        public Criteria andPublYearNotBetween(String value1, String value2) {
            addCriterion("PUBL_YEAR not between", value1, value2, "publYear");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andAttachmentIsNull() {
            addCriterion("ATTACHMENT is null");
            return (Criteria) this;
        }

        public Criteria andAttachmentIsNotNull() {
            addCriterion("ATTACHMENT is not null");
            return (Criteria) this;
        }

        public Criteria andAttachmentEqualTo(String value) {
            addCriterion("ATTACHMENT =", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentNotEqualTo(String value) {
            addCriterion("ATTACHMENT <>", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentGreaterThan(String value) {
            addCriterion("ATTACHMENT >", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentGreaterThanOrEqualTo(String value) {
            addCriterion("ATTACHMENT >=", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentLessThan(String value) {
            addCriterion("ATTACHMENT <", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentLessThanOrEqualTo(String value) {
            addCriterion("ATTACHMENT <=", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentLike(String value) {
            addCriterion("ATTACHMENT like", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentNotLike(String value) {
            addCriterion("ATTACHMENT not like", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentIn(List<String> values) {
            addCriterion("ATTACHMENT in", values, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentNotIn(List<String> values) {
            addCriterion("ATTACHMENT not in", values, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentBetween(String value1, String value2) {
            addCriterion("ATTACHMENT between", value1, value2, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentNotBetween(String value1, String value2) {
            addCriterion("ATTACHMENT not between", value1, value2, "attachment");
            return (Criteria) this;
        }

        public Criteria andIssueTitleIsNull() {
            addCriterion("ISSUE_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andIssueTitleIsNotNull() {
            addCriterion("ISSUE_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andIssueTitleEqualTo(String value) {
            addCriterion("ISSUE_TITLE =", value, "issueTitle");
            return (Criteria) this;
        }

        public Criteria andIssueTitleNotEqualTo(String value) {
            addCriterion("ISSUE_TITLE <>", value, "issueTitle");
            return (Criteria) this;
        }

        public Criteria andIssueTitleGreaterThan(String value) {
            addCriterion("ISSUE_TITLE >", value, "issueTitle");
            return (Criteria) this;
        }

        public Criteria andIssueTitleGreaterThanOrEqualTo(String value) {
            addCriterion("ISSUE_TITLE >=", value, "issueTitle");
            return (Criteria) this;
        }

        public Criteria andIssueTitleLessThan(String value) {
            addCriterion("ISSUE_TITLE <", value, "issueTitle");
            return (Criteria) this;
        }

        public Criteria andIssueTitleLessThanOrEqualTo(String value) {
            addCriterion("ISSUE_TITLE <=", value, "issueTitle");
            return (Criteria) this;
        }

        public Criteria andIssueTitleLike(String value) {
            addCriterion("ISSUE_TITLE like", value, "issueTitle");
            return (Criteria) this;
        }

        public Criteria andIssueTitleNotLike(String value) {
            addCriterion("ISSUE_TITLE not like", value, "issueTitle");
            return (Criteria) this;
        }

        public Criteria andIssueTitleIn(List<String> values) {
            addCriterion("ISSUE_TITLE in", values, "issueTitle");
            return (Criteria) this;
        }

        public Criteria andIssueTitleNotIn(List<String> values) {
            addCriterion("ISSUE_TITLE not in", values, "issueTitle");
            return (Criteria) this;
        }

        public Criteria andIssueTitleBetween(String value1, String value2) {
            addCriterion("ISSUE_TITLE between", value1, value2, "issueTitle");
            return (Criteria) this;
        }

        public Criteria andIssueTitleNotBetween(String value1, String value2) {
            addCriterion("ISSUE_TITLE not between", value1, value2, "issueTitle");
            return (Criteria) this;
        }

        public Criteria andBeginVolIsNull() {
            addCriterion("BEGIN_VOL is null");
            return (Criteria) this;
        }

        public Criteria andBeginVolIsNotNull() {
            addCriterion("BEGIN_VOL is not null");
            return (Criteria) this;
        }

        public Criteria andBeginVolEqualTo(String value) {
            addCriterion("BEGIN_VOL =", value, "beginVol");
            return (Criteria) this;
        }

        public Criteria andBeginVolNotEqualTo(String value) {
            addCriterion("BEGIN_VOL <>", value, "beginVol");
            return (Criteria) this;
        }

        public Criteria andBeginVolGreaterThan(String value) {
            addCriterion("BEGIN_VOL >", value, "beginVol");
            return (Criteria) this;
        }

        public Criteria andBeginVolGreaterThanOrEqualTo(String value) {
            addCriterion("BEGIN_VOL >=", value, "beginVol");
            return (Criteria) this;
        }

        public Criteria andBeginVolLessThan(String value) {
            addCriterion("BEGIN_VOL <", value, "beginVol");
            return (Criteria) this;
        }

        public Criteria andBeginVolLessThanOrEqualTo(String value) {
            addCriterion("BEGIN_VOL <=", value, "beginVol");
            return (Criteria) this;
        }

        public Criteria andBeginVolLike(String value) {
            addCriterion("BEGIN_VOL like", value, "beginVol");
            return (Criteria) this;
        }

        public Criteria andBeginVolNotLike(String value) {
            addCriterion("BEGIN_VOL not like", value, "beginVol");
            return (Criteria) this;
        }

        public Criteria andBeginVolIn(List<String> values) {
            addCriterion("BEGIN_VOL in", values, "beginVol");
            return (Criteria) this;
        }

        public Criteria andBeginVolNotIn(List<String> values) {
            addCriterion("BEGIN_VOL not in", values, "beginVol");
            return (Criteria) this;
        }

        public Criteria andBeginVolBetween(String value1, String value2) {
            addCriterion("BEGIN_VOL between", value1, value2, "beginVol");
            return (Criteria) this;
        }

        public Criteria andBeginVolNotBetween(String value1, String value2) {
            addCriterion("BEGIN_VOL not between", value1, value2, "beginVol");
            return (Criteria) this;
        }

        public Criteria andEndVolIsNull() {
            addCriterion("END_VOL is null");
            return (Criteria) this;
        }

        public Criteria andEndVolIsNotNull() {
            addCriterion("END_VOL is not null");
            return (Criteria) this;
        }

        public Criteria andEndVolEqualTo(String value) {
            addCriterion("END_VOL =", value, "endVol");
            return (Criteria) this;
        }

        public Criteria andEndVolNotEqualTo(String value) {
            addCriterion("END_VOL <>", value, "endVol");
            return (Criteria) this;
        }

        public Criteria andEndVolGreaterThan(String value) {
            addCriterion("END_VOL >", value, "endVol");
            return (Criteria) this;
        }

        public Criteria andEndVolGreaterThanOrEqualTo(String value) {
            addCriterion("END_VOL >=", value, "endVol");
            return (Criteria) this;
        }

        public Criteria andEndVolLessThan(String value) {
            addCriterion("END_VOL <", value, "endVol");
            return (Criteria) this;
        }

        public Criteria andEndVolLessThanOrEqualTo(String value) {
            addCriterion("END_VOL <=", value, "endVol");
            return (Criteria) this;
        }

        public Criteria andEndVolLike(String value) {
            addCriterion("END_VOL like", value, "endVol");
            return (Criteria) this;
        }

        public Criteria andEndVolNotLike(String value) {
            addCriterion("END_VOL not like", value, "endVol");
            return (Criteria) this;
        }

        public Criteria andEndVolIn(List<String> values) {
            addCriterion("END_VOL in", values, "endVol");
            return (Criteria) this;
        }

        public Criteria andEndVolNotIn(List<String> values) {
            addCriterion("END_VOL not in", values, "endVol");
            return (Criteria) this;
        }

        public Criteria andEndVolBetween(String value1, String value2) {
            addCriterion("END_VOL between", value1, value2, "endVol");
            return (Criteria) this;
        }

        public Criteria andEndVolNotBetween(String value1, String value2) {
            addCriterion("END_VOL not between", value1, value2, "endVol");
            return (Criteria) this;
        }

        public Criteria andBeginIssueIsNull() {
            addCriterion("BEGIN_ISSUE is null");
            return (Criteria) this;
        }

        public Criteria andBeginIssueIsNotNull() {
            addCriterion("BEGIN_ISSUE is not null");
            return (Criteria) this;
        }

        public Criteria andBeginIssueEqualTo(String value) {
            addCriterion("BEGIN_ISSUE =", value, "beginIssue");
            return (Criteria) this;
        }

        public Criteria andBeginIssueNotEqualTo(String value) {
            addCriterion("BEGIN_ISSUE <>", value, "beginIssue");
            return (Criteria) this;
        }

        public Criteria andBeginIssueGreaterThan(String value) {
            addCriterion("BEGIN_ISSUE >", value, "beginIssue");
            return (Criteria) this;
        }

        public Criteria andBeginIssueGreaterThanOrEqualTo(String value) {
            addCriterion("BEGIN_ISSUE >=", value, "beginIssue");
            return (Criteria) this;
        }

        public Criteria andBeginIssueLessThan(String value) {
            addCriterion("BEGIN_ISSUE <", value, "beginIssue");
            return (Criteria) this;
        }

        public Criteria andBeginIssueLessThanOrEqualTo(String value) {
            addCriterion("BEGIN_ISSUE <=", value, "beginIssue");
            return (Criteria) this;
        }

        public Criteria andBeginIssueLike(String value) {
            addCriterion("BEGIN_ISSUE like", value, "beginIssue");
            return (Criteria) this;
        }

        public Criteria andBeginIssueNotLike(String value) {
            addCriterion("BEGIN_ISSUE not like", value, "beginIssue");
            return (Criteria) this;
        }

        public Criteria andBeginIssueIn(List<String> values) {
            addCriterion("BEGIN_ISSUE in", values, "beginIssue");
            return (Criteria) this;
        }

        public Criteria andBeginIssueNotIn(List<String> values) {
            addCriterion("BEGIN_ISSUE not in", values, "beginIssue");
            return (Criteria) this;
        }

        public Criteria andBeginIssueBetween(String value1, String value2) {
            addCriterion("BEGIN_ISSUE between", value1, value2, "beginIssue");
            return (Criteria) this;
        }

        public Criteria andBeginIssueNotBetween(String value1, String value2) {
            addCriterion("BEGIN_ISSUE not between", value1, value2, "beginIssue");
            return (Criteria) this;
        }

        public Criteria andEndIssueIsNull() {
            addCriterion("END_ISSUE is null");
            return (Criteria) this;
        }

        public Criteria andEndIssueIsNotNull() {
            addCriterion("END_ISSUE is not null");
            return (Criteria) this;
        }

        public Criteria andEndIssueEqualTo(String value) {
            addCriterion("END_ISSUE =", value, "endIssue");
            return (Criteria) this;
        }

        public Criteria andEndIssueNotEqualTo(String value) {
            addCriterion("END_ISSUE <>", value, "endIssue");
            return (Criteria) this;
        }

        public Criteria andEndIssueGreaterThan(String value) {
            addCriterion("END_ISSUE >", value, "endIssue");
            return (Criteria) this;
        }

        public Criteria andEndIssueGreaterThanOrEqualTo(String value) {
            addCriterion("END_ISSUE >=", value, "endIssue");
            return (Criteria) this;
        }

        public Criteria andEndIssueLessThan(String value) {
            addCriterion("END_ISSUE <", value, "endIssue");
            return (Criteria) this;
        }

        public Criteria andEndIssueLessThanOrEqualTo(String value) {
            addCriterion("END_ISSUE <=", value, "endIssue");
            return (Criteria) this;
        }

        public Criteria andEndIssueLike(String value) {
            addCriterion("END_ISSUE like", value, "endIssue");
            return (Criteria) this;
        }

        public Criteria andEndIssueNotLike(String value) {
            addCriterion("END_ISSUE not like", value, "endIssue");
            return (Criteria) this;
        }

        public Criteria andEndIssueIn(List<String> values) {
            addCriterion("END_ISSUE in", values, "endIssue");
            return (Criteria) this;
        }

        public Criteria andEndIssueNotIn(List<String> values) {
            addCriterion("END_ISSUE not in", values, "endIssue");
            return (Criteria) this;
        }

        public Criteria andEndIssueBetween(String value1, String value2) {
            addCriterion("END_ISSUE between", value1, value2, "endIssue");
            return (Criteria) this;
        }

        public Criteria andEndIssueNotBetween(String value1, String value2) {
            addCriterion("END_ISSUE not between", value1, value2, "endIssue");
            return (Criteria) this;
        }

        public Criteria andImageAddressIsNull() {
            addCriterion("IMAGE_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andImageAddressIsNotNull() {
            addCriterion("IMAGE_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andImageAddressEqualTo(String value) {
            addCriterion("IMAGE_ADDRESS =", value, "imageAddress");
            return (Criteria) this;
        }

        public Criteria andImageAddressNotEqualTo(String value) {
            addCriterion("IMAGE_ADDRESS <>", value, "imageAddress");
            return (Criteria) this;
        }

        public Criteria andImageAddressGreaterThan(String value) {
            addCriterion("IMAGE_ADDRESS >", value, "imageAddress");
            return (Criteria) this;
        }

        public Criteria andImageAddressGreaterThanOrEqualTo(String value) {
            addCriterion("IMAGE_ADDRESS >=", value, "imageAddress");
            return (Criteria) this;
        }

        public Criteria andImageAddressLessThan(String value) {
            addCriterion("IMAGE_ADDRESS <", value, "imageAddress");
            return (Criteria) this;
        }

        public Criteria andImageAddressLessThanOrEqualTo(String value) {
            addCriterion("IMAGE_ADDRESS <=", value, "imageAddress");
            return (Criteria) this;
        }

        public Criteria andImageAddressLike(String value) {
            addCriterion("IMAGE_ADDRESS like", value, "imageAddress");
            return (Criteria) this;
        }

        public Criteria andImageAddressNotLike(String value) {
            addCriterion("IMAGE_ADDRESS not like", value, "imageAddress");
            return (Criteria) this;
        }

        public Criteria andImageAddressIn(List<String> values) {
            addCriterion("IMAGE_ADDRESS in", values, "imageAddress");
            return (Criteria) this;
        }

        public Criteria andImageAddressNotIn(List<String> values) {
            addCriterion("IMAGE_ADDRESS not in", values, "imageAddress");
            return (Criteria) this;
        }

        public Criteria andImageAddressBetween(String value1, String value2) {
            addCriterion("IMAGE_ADDRESS between", value1, value2, "imageAddress");
            return (Criteria) this;
        }

        public Criteria andImageAddressNotBetween(String value1, String value2) {
            addCriterion("IMAGE_ADDRESS not between", value1, value2, "imageAddress");
            return (Criteria) this;
        }

        public Criteria andPeriTypeIsNull() {
            addCriterion("PERI_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPeriTypeIsNotNull() {
            addCriterion("PERI_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPeriTypeEqualTo(Integer value) {
            addCriterion("PERI_TYPE =", value, "periType");
            return (Criteria) this;
        }

        public Criteria andPeriTypeNotEqualTo(Integer value) {
            addCriterion("PERI_TYPE <>", value, "periType");
            return (Criteria) this;
        }

        public Criteria andPeriTypeGreaterThan(Integer value) {
            addCriterion("PERI_TYPE >", value, "periType");
            return (Criteria) this;
        }

        public Criteria andPeriTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PERI_TYPE >=", value, "periType");
            return (Criteria) this;
        }

        public Criteria andPeriTypeLessThan(Integer value) {
            addCriterion("PERI_TYPE <", value, "periType");
            return (Criteria) this;
        }

        public Criteria andPeriTypeLessThanOrEqualTo(Integer value) {
            addCriterion("PERI_TYPE <=", value, "periType");
            return (Criteria) this;
        }

        public Criteria andPeriTypeIn(List<Integer> values) {
            addCriterion("PERI_TYPE in", values, "periType");
            return (Criteria) this;
        }

        public Criteria andPeriTypeNotIn(List<Integer> values) {
            addCriterion("PERI_TYPE not in", values, "periType");
            return (Criteria) this;
        }

        public Criteria andPeriTypeBetween(Integer value1, Integer value2) {
            addCriterion("PERI_TYPE between", value1, value2, "periType");
            return (Criteria) this;
        }

        public Criteria andPeriTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("PERI_TYPE not between", value1, value2, "periType");
            return (Criteria) this;
        }

        public Criteria andPeriPriceIsNull() {
            addCriterion("PERI_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andPeriPriceIsNotNull() {
            addCriterion("PERI_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andPeriPriceEqualTo(BigDecimal value) {
            addCriterion("PERI_PRICE =", value, "periPrice");
            return (Criteria) this;
        }

        public Criteria andPeriPriceNotEqualTo(BigDecimal value) {
            addCriterion("PERI_PRICE <>", value, "periPrice");
            return (Criteria) this;
        }

        public Criteria andPeriPriceGreaterThan(BigDecimal value) {
            addCriterion("PERI_PRICE >", value, "periPrice");
            return (Criteria) this;
        }

        public Criteria andPeriPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PERI_PRICE >=", value, "periPrice");
            return (Criteria) this;
        }

        public Criteria andPeriPriceLessThan(BigDecimal value) {
            addCriterion("PERI_PRICE <", value, "periPrice");
            return (Criteria) this;
        }

        public Criteria andPeriPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PERI_PRICE <=", value, "periPrice");
            return (Criteria) this;
        }

        public Criteria andPeriPriceIn(List<BigDecimal> values) {
            addCriterion("PERI_PRICE in", values, "periPrice");
            return (Criteria) this;
        }

        public Criteria andPeriPriceNotIn(List<BigDecimal> values) {
            addCriterion("PERI_PRICE not in", values, "periPrice");
            return (Criteria) this;
        }

        public Criteria andPeriPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PERI_PRICE between", value1, value2, "periPrice");
            return (Criteria) this;
        }

        public Criteria andPeriPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PERI_PRICE not between", value1, value2, "periPrice");
            return (Criteria) this;
        }

        public Criteria andPeriTotalPriceIsNull() {
            addCriterion("PERI_TOTAL_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andPeriTotalPriceIsNotNull() {
            addCriterion("PERI_TOTAL_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andPeriTotalPriceEqualTo(BigDecimal value) {
            addCriterion("PERI_TOTAL_PRICE =", value, "periTotalPrice");
            return (Criteria) this;
        }

        public Criteria andPeriTotalPriceNotEqualTo(BigDecimal value) {
            addCriterion("PERI_TOTAL_PRICE <>", value, "periTotalPrice");
            return (Criteria) this;
        }

        public Criteria andPeriTotalPriceGreaterThan(BigDecimal value) {
            addCriterion("PERI_TOTAL_PRICE >", value, "periTotalPrice");
            return (Criteria) this;
        }

        public Criteria andPeriTotalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PERI_TOTAL_PRICE >=", value, "periTotalPrice");
            return (Criteria) this;
        }

        public Criteria andPeriTotalPriceLessThan(BigDecimal value) {
            addCriterion("PERI_TOTAL_PRICE <", value, "periTotalPrice");
            return (Criteria) this;
        }

        public Criteria andPeriTotalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PERI_TOTAL_PRICE <=", value, "periTotalPrice");
            return (Criteria) this;
        }

        public Criteria andPeriTotalPriceIn(List<BigDecimal> values) {
            addCriterion("PERI_TOTAL_PRICE in", values, "periTotalPrice");
            return (Criteria) this;
        }

        public Criteria andPeriTotalPriceNotIn(List<BigDecimal> values) {
            addCriterion("PERI_TOTAL_PRICE not in", values, "periTotalPrice");
            return (Criteria) this;
        }

        public Criteria andPeriTotalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PERI_TOTAL_PRICE between", value1, value2, "periTotalPrice");
            return (Criteria) this;
        }

        public Criteria andPeriTotalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PERI_TOTAL_PRICE not between", value1, value2, "periTotalPrice");
            return (Criteria) this;
        }

        public Criteria andForePriceIsNull() {
            addCriterion("FORE_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andForePriceIsNotNull() {
            addCriterion("FORE_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andForePriceEqualTo(BigDecimal value) {
            addCriterion("FORE_PRICE =", value, "forePrice");
            return (Criteria) this;
        }

        public Criteria andForePriceNotEqualTo(BigDecimal value) {
            addCriterion("FORE_PRICE <>", value, "forePrice");
            return (Criteria) this;
        }

        public Criteria andForePriceGreaterThan(BigDecimal value) {
            addCriterion("FORE_PRICE >", value, "forePrice");
            return (Criteria) this;
        }

        public Criteria andForePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FORE_PRICE >=", value, "forePrice");
            return (Criteria) this;
        }

        public Criteria andForePriceLessThan(BigDecimal value) {
            addCriterion("FORE_PRICE <", value, "forePrice");
            return (Criteria) this;
        }

        public Criteria andForePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FORE_PRICE <=", value, "forePrice");
            return (Criteria) this;
        }

        public Criteria andForePriceIn(List<BigDecimal> values) {
            addCriterion("FORE_PRICE in", values, "forePrice");
            return (Criteria) this;
        }

        public Criteria andForePriceNotIn(List<BigDecimal> values) {
            addCriterion("FORE_PRICE not in", values, "forePrice");
            return (Criteria) this;
        }

        public Criteria andForePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FORE_PRICE between", value1, value2, "forePrice");
            return (Criteria) this;
        }

        public Criteria andForePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FORE_PRICE not between", value1, value2, "forePrice");
            return (Criteria) this;
        }

        public Criteria andForeTotalPriceIsNull() {
            addCriterion("FORE_TOTAL_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andForeTotalPriceIsNotNull() {
            addCriterion("FORE_TOTAL_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andForeTotalPriceEqualTo(BigDecimal value) {
            addCriterion("FORE_TOTAL_PRICE =", value, "foreTotalPrice");
            return (Criteria) this;
        }

        public Criteria andForeTotalPriceNotEqualTo(BigDecimal value) {
            addCriterion("FORE_TOTAL_PRICE <>", value, "foreTotalPrice");
            return (Criteria) this;
        }

        public Criteria andForeTotalPriceGreaterThan(BigDecimal value) {
            addCriterion("FORE_TOTAL_PRICE >", value, "foreTotalPrice");
            return (Criteria) this;
        }

        public Criteria andForeTotalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FORE_TOTAL_PRICE >=", value, "foreTotalPrice");
            return (Criteria) this;
        }

        public Criteria andForeTotalPriceLessThan(BigDecimal value) {
            addCriterion("FORE_TOTAL_PRICE <", value, "foreTotalPrice");
            return (Criteria) this;
        }

        public Criteria andForeTotalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FORE_TOTAL_PRICE <=", value, "foreTotalPrice");
            return (Criteria) this;
        }

        public Criteria andForeTotalPriceIn(List<BigDecimal> values) {
            addCriterion("FORE_TOTAL_PRICE in", values, "foreTotalPrice");
            return (Criteria) this;
        }

        public Criteria andForeTotalPriceNotIn(List<BigDecimal> values) {
            addCriterion("FORE_TOTAL_PRICE not in", values, "foreTotalPrice");
            return (Criteria) this;
        }

        public Criteria andForeTotalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FORE_TOTAL_PRICE between", value1, value2, "foreTotalPrice");
            return (Criteria) this;
        }

        public Criteria andForeTotalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FORE_TOTAL_PRICE not between", value1, value2, "foreTotalPrice");
            return (Criteria) this;
        }

        public Criteria andQtyOfYearIsNull() {
            addCriterion("QTY_OF_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andQtyOfYearIsNotNull() {
            addCriterion("QTY_OF_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andQtyOfYearEqualTo(Integer value) {
            addCriterion("QTY_OF_YEAR =", value, "qtyOfYear");
            return (Criteria) this;
        }

        public Criteria andQtyOfYearNotEqualTo(Integer value) {
            addCriterion("QTY_OF_YEAR <>", value, "qtyOfYear");
            return (Criteria) this;
        }

        public Criteria andQtyOfYearGreaterThan(Integer value) {
            addCriterion("QTY_OF_YEAR >", value, "qtyOfYear");
            return (Criteria) this;
        }

        public Criteria andQtyOfYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("QTY_OF_YEAR >=", value, "qtyOfYear");
            return (Criteria) this;
        }

        public Criteria andQtyOfYearLessThan(Integer value) {
            addCriterion("QTY_OF_YEAR <", value, "qtyOfYear");
            return (Criteria) this;
        }

        public Criteria andQtyOfYearLessThanOrEqualTo(Integer value) {
            addCriterion("QTY_OF_YEAR <=", value, "qtyOfYear");
            return (Criteria) this;
        }

        public Criteria andQtyOfYearIn(List<Integer> values) {
            addCriterion("QTY_OF_YEAR in", values, "qtyOfYear");
            return (Criteria) this;
        }

        public Criteria andQtyOfYearNotIn(List<Integer> values) {
            addCriterion("QTY_OF_YEAR not in", values, "qtyOfYear");
            return (Criteria) this;
        }

        public Criteria andQtyOfYearBetween(Integer value1, Integer value2) {
            addCriterion("QTY_OF_YEAR between", value1, value2, "qtyOfYear");
            return (Criteria) this;
        }

        public Criteria andQtyOfYearNotBetween(Integer value1, Integer value2) {
            addCriterion("QTY_OF_YEAR not between", value1, value2, "qtyOfYear");
            return (Criteria) this;
        }

        public Criteria andQtyOfVolIsNull() {
            addCriterion("QTY_OF_VOL is null");
            return (Criteria) this;
        }

        public Criteria andQtyOfVolIsNotNull() {
            addCriterion("QTY_OF_VOL is not null");
            return (Criteria) this;
        }

        public Criteria andQtyOfVolEqualTo(Integer value) {
            addCriterion("QTY_OF_VOL =", value, "qtyOfVol");
            return (Criteria) this;
        }

        public Criteria andQtyOfVolNotEqualTo(Integer value) {
            addCriterion("QTY_OF_VOL <>", value, "qtyOfVol");
            return (Criteria) this;
        }

        public Criteria andQtyOfVolGreaterThan(Integer value) {
            addCriterion("QTY_OF_VOL >", value, "qtyOfVol");
            return (Criteria) this;
        }

        public Criteria andQtyOfVolGreaterThanOrEqualTo(Integer value) {
            addCriterion("QTY_OF_VOL >=", value, "qtyOfVol");
            return (Criteria) this;
        }

        public Criteria andQtyOfVolLessThan(Integer value) {
            addCriterion("QTY_OF_VOL <", value, "qtyOfVol");
            return (Criteria) this;
        }

        public Criteria andQtyOfVolLessThanOrEqualTo(Integer value) {
            addCriterion("QTY_OF_VOL <=", value, "qtyOfVol");
            return (Criteria) this;
        }

        public Criteria andQtyOfVolIn(List<Integer> values) {
            addCriterion("QTY_OF_VOL in", values, "qtyOfVol");
            return (Criteria) this;
        }

        public Criteria andQtyOfVolNotIn(List<Integer> values) {
            addCriterion("QTY_OF_VOL not in", values, "qtyOfVol");
            return (Criteria) this;
        }

        public Criteria andQtyOfVolBetween(Integer value1, Integer value2) {
            addCriterion("QTY_OF_VOL between", value1, value2, "qtyOfVol");
            return (Criteria) this;
        }

        public Criteria andQtyOfVolNotBetween(Integer value1, Integer value2) {
            addCriterion("QTY_OF_VOL not between", value1, value2, "qtyOfVol");
            return (Criteria) this;
        }

        public Criteria andDaysOfItemsIsNull() {
            addCriterion("DAYS_OF_ITEMS is null");
            return (Criteria) this;
        }

        public Criteria andDaysOfItemsIsNotNull() {
            addCriterion("DAYS_OF_ITEMS is not null");
            return (Criteria) this;
        }

        public Criteria andDaysOfItemsEqualTo(Integer value) {
            addCriterion("DAYS_OF_ITEMS =", value, "daysOfItems");
            return (Criteria) this;
        }

        public Criteria andDaysOfItemsNotEqualTo(Integer value) {
            addCriterion("DAYS_OF_ITEMS <>", value, "daysOfItems");
            return (Criteria) this;
        }

        public Criteria andDaysOfItemsGreaterThan(Integer value) {
            addCriterion("DAYS_OF_ITEMS >", value, "daysOfItems");
            return (Criteria) this;
        }

        public Criteria andDaysOfItemsGreaterThanOrEqualTo(Integer value) {
            addCriterion("DAYS_OF_ITEMS >=", value, "daysOfItems");
            return (Criteria) this;
        }

        public Criteria andDaysOfItemsLessThan(Integer value) {
            addCriterion("DAYS_OF_ITEMS <", value, "daysOfItems");
            return (Criteria) this;
        }

        public Criteria andDaysOfItemsLessThanOrEqualTo(Integer value) {
            addCriterion("DAYS_OF_ITEMS <=", value, "daysOfItems");
            return (Criteria) this;
        }

        public Criteria andDaysOfItemsIn(List<Integer> values) {
            addCriterion("DAYS_OF_ITEMS in", values, "daysOfItems");
            return (Criteria) this;
        }

        public Criteria andDaysOfItemsNotIn(List<Integer> values) {
            addCriterion("DAYS_OF_ITEMS not in", values, "daysOfItems");
            return (Criteria) this;
        }

        public Criteria andDaysOfItemsBetween(Integer value1, Integer value2) {
            addCriterion("DAYS_OF_ITEMS between", value1, value2, "daysOfItems");
            return (Criteria) this;
        }

        public Criteria andDaysOfItemsNotBetween(Integer value1, Integer value2) {
            addCriterion("DAYS_OF_ITEMS not between", value1, value2, "daysOfItems");
            return (Criteria) this;
        }

        public Criteria andPublFreqCodeIsNull() {
            addCriterion("PUBL_FREQ_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPublFreqCodeIsNotNull() {
            addCriterion("PUBL_FREQ_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPublFreqCodeEqualTo(Integer value) {
            addCriterion("PUBL_FREQ_CODE =", value, "publFreqCode");
            return (Criteria) this;
        }

        public Criteria andPublFreqCodeNotEqualTo(Integer value) {
            addCriterion("PUBL_FREQ_CODE <>", value, "publFreqCode");
            return (Criteria) this;
        }

        public Criteria andPublFreqCodeGreaterThan(Integer value) {
            addCriterion("PUBL_FREQ_CODE >", value, "publFreqCode");
            return (Criteria) this;
        }

        public Criteria andPublFreqCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PUBL_FREQ_CODE >=", value, "publFreqCode");
            return (Criteria) this;
        }

        public Criteria andPublFreqCodeLessThan(Integer value) {
            addCriterion("PUBL_FREQ_CODE <", value, "publFreqCode");
            return (Criteria) this;
        }

        public Criteria andPublFreqCodeLessThanOrEqualTo(Integer value) {
            addCriterion("PUBL_FREQ_CODE <=", value, "publFreqCode");
            return (Criteria) this;
        }

        public Criteria andPublFreqCodeIn(List<Integer> values) {
            addCriterion("PUBL_FREQ_CODE in", values, "publFreqCode");
            return (Criteria) this;
        }

        public Criteria andPublFreqCodeNotIn(List<Integer> values) {
            addCriterion("PUBL_FREQ_CODE not in", values, "publFreqCode");
            return (Criteria) this;
        }

        public Criteria andPublFreqCodeBetween(Integer value1, Integer value2) {
            addCriterion("PUBL_FREQ_CODE between", value1, value2, "publFreqCode");
            return (Criteria) this;
        }

        public Criteria andPublFreqCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("PUBL_FREQ_CODE not between", value1, value2, "publFreqCode");
            return (Criteria) this;
        }

        public Criteria andMarcIdIsNull() {
            addCriterion("MARC_ID is null");
            return (Criteria) this;
        }

        public Criteria andMarcIdIsNotNull() {
            addCriterion("MARC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMarcIdEqualTo(Integer value) {
            addCriterion("MARC_ID =", value, "marcId");
            return (Criteria) this;
        }

        public Criteria andMarcIdNotEqualTo(Integer value) {
            addCriterion("MARC_ID <>", value, "marcId");
            return (Criteria) this;
        }

        public Criteria andMarcIdGreaterThan(Integer value) {
            addCriterion("MARC_ID >", value, "marcId");
            return (Criteria) this;
        }

        public Criteria andMarcIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("MARC_ID >=", value, "marcId");
            return (Criteria) this;
        }

        public Criteria andMarcIdLessThan(Integer value) {
            addCriterion("MARC_ID <", value, "marcId");
            return (Criteria) this;
        }

        public Criteria andMarcIdLessThanOrEqualTo(Integer value) {
            addCriterion("MARC_ID <=", value, "marcId");
            return (Criteria) this;
        }

        public Criteria andMarcIdIn(List<Integer> values) {
            addCriterion("MARC_ID in", values, "marcId");
            return (Criteria) this;
        }

        public Criteria andMarcIdNotIn(List<Integer> values) {
            addCriterion("MARC_ID not in", values, "marcId");
            return (Criteria) this;
        }

        public Criteria andMarcIdBetween(Integer value1, Integer value2) {
            addCriterion("MARC_ID between", value1, value2, "marcId");
            return (Criteria) this;
        }

        public Criteria andMarcIdNotBetween(Integer value1, Integer value2) {
            addCriterion("MARC_ID not between", value1, value2, "marcId");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("ADD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("ADD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("ADD_TIME =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("ADD_TIME <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("ADD_TIME >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("ADD_TIME <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("ADD_TIME in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("ADD_TIME not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME not between", value1, value2, "addTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table down_peri_vol_lst
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table down_peri_vol_lst
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}