package com.gk.webmagic.demo2.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table down_peri_vol_lst
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class DownPeriVolLst {
    /**
     * Database Column Remarks:
     *   期刊收登标识号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.PERI_VOL_ID
     *
     * @mbg.generated
     */
    private Integer periVolId;

    /**
     * Database Column Remarks:
     *   期刊编号ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.DOC_ID
     *
     * @mbg.generated
     */
    private String docId;

    /**
     * Database Column Remarks:
     *   开本尺寸
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.BOOK_SIZE_CODE
     *
     * @mbg.generated
     */
    private Integer bookSizeCode;

    /**
     * Database Column Remarks:
     *   货币代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.CURRENCY_CODE
     *
     * @mbg.generated
     */
    private Integer currencyCode;

    /**
     * Database Column Remarks:
     *   载体代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.CARRIER_CODE
     *
     * @mbg.generated
     */
    private String carrierCode;

    /**
     * Database Column Remarks:
     *   封面卷
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.COVER_VOL
     *
     * @mbg.generated
     */
    private String coverVol;

    /**
     * Database Column Remarks:
     *   封面期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.COVER_ISSUE
     *
     * @mbg.generated
     */
    private String coverIssue;

    /**
     * Database Column Remarks:
     *   总期数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.COVER_ISSUE_TOTAL
     *
     * @mbg.generated
     */
    private String coverIssueTotal;

    /**
     * Database Column Remarks:
     *   预到日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.EXPECT_DATE
     *
     * @mbg.generated
     */
    private Date expectDate;

    /**
     * Database Column Remarks:
     *   出版年度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.PUBL_YEAR
     *
     * @mbg.generated
     */
    private String publYear;

    /**
     * Database Column Remarks:
     *   说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   附件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.ATTACHMENT
     *
     * @mbg.generated
     */
    private String attachment;

    /**
     * Database Column Remarks:
     *   期题名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.ISSUE_TITLE
     *
     * @mbg.generated
     */
    private String issueTitle;

    /**
     * Database Column Remarks:
     *   起始卷
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.BEGIN_VOL
     *
     * @mbg.generated
     */
    private String beginVol;

    /**
     * Database Column Remarks:
     *   截止卷
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.END_VOL
     *
     * @mbg.generated
     */
    private String endVol;

    /**
     * Database Column Remarks:
     *   起始期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.BEGIN_ISSUE
     *
     * @mbg.generated
     */
    private String beginIssue;

    /**
     * Database Column Remarks:
     *   截止期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.END_ISSUE
     *
     * @mbg.generated
     */
    private String endIssue;

    /**
     * Database Column Remarks:
     *   图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.IMAGE_ADDRESS
     *
     * @mbg.generated
     */
    private String imageAddress;

    /**
     * Database Column Remarks:
     *   期刊类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.PERI_TYPE
     *
     * @mbg.generated
     */
    private Integer periType;

    /**
     * Database Column Remarks:
     *   单价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.PERI_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal periPrice;

    /**
     * Database Column Remarks:
     *   总价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.PERI_TOTAL_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal periTotalPrice;

    /**
     * Database Column Remarks:
     *   外汇单价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.FORE_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal forePrice;

    /**
     * Database Column Remarks:
     *   外汇总价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.FORE_TOTAL_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal foreTotalPrice;

    /**
     * Database Column Remarks:
     *   每年期数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.QTY_OF_YEAR
     *
     * @mbg.generated
     */
    private Integer qtyOfYear;

    /**
     * Database Column Remarks:
     *   每卷期数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.QTY_OF_VOL
     *
     * @mbg.generated
     */
    private Integer qtyOfVol;

    /**
     * Database Column Remarks:
     *   每期间隔天数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.DAYS_OF_ITEMS
     *
     * @mbg.generated
     */
    private Integer daysOfItems;

    /**
     * Database Column Remarks:
     *   出版频率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.PUBL_FREQ_CODE
     *
     * @mbg.generated
     */
    private Integer publFreqCode;

    /**
     * Database Column Remarks:
     *   关联期刊ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.MARC_ID
     *
     * @mbg.generated
     */
    private Integer marcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.ADD_TIME
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     * Database Column Remarks:
     *   目录
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_vol_lst.CATALOG
     *
     * @mbg.generated
     */
    private String catalog;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.PERI_VOL_ID
     *
     * @return the value of down_peri_vol_lst.PERI_VOL_ID
     *
     * @mbg.generated
     */
    public Integer getPeriVolId() {
        return periVolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.PERI_VOL_ID
     *
     * @param periVolId the value for down_peri_vol_lst.PERI_VOL_ID
     *
     * @mbg.generated
     */
    public void setPeriVolId(Integer periVolId) {
        this.periVolId = periVolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.DOC_ID
     *
     * @return the value of down_peri_vol_lst.DOC_ID
     *
     * @mbg.generated
     */
    public String getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.DOC_ID
     *
     * @param docId the value for down_peri_vol_lst.DOC_ID
     *
     * @mbg.generated
     */
    public void setDocId(String docId) {
        this.docId = docId == null ? null : docId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.BOOK_SIZE_CODE
     *
     * @return the value of down_peri_vol_lst.BOOK_SIZE_CODE
     *
     * @mbg.generated
     */
    public Integer getBookSizeCode() {
        return bookSizeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.BOOK_SIZE_CODE
     *
     * @param bookSizeCode the value for down_peri_vol_lst.BOOK_SIZE_CODE
     *
     * @mbg.generated
     */
    public void setBookSizeCode(Integer bookSizeCode) {
        this.bookSizeCode = bookSizeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.CURRENCY_CODE
     *
     * @return the value of down_peri_vol_lst.CURRENCY_CODE
     *
     * @mbg.generated
     */
    public Integer getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.CURRENCY_CODE
     *
     * @param currencyCode the value for down_peri_vol_lst.CURRENCY_CODE
     *
     * @mbg.generated
     */
    public void setCurrencyCode(Integer currencyCode) {
        this.currencyCode = currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.CARRIER_CODE
     *
     * @return the value of down_peri_vol_lst.CARRIER_CODE
     *
     * @mbg.generated
     */
    public String getCarrierCode() {
        return carrierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.CARRIER_CODE
     *
     * @param carrierCode the value for down_peri_vol_lst.CARRIER_CODE
     *
     * @mbg.generated
     */
    public void setCarrierCode(String carrierCode) {
        this.carrierCode = carrierCode == null ? null : carrierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.COVER_VOL
     *
     * @return the value of down_peri_vol_lst.COVER_VOL
     *
     * @mbg.generated
     */
    public String getCoverVol() {
        return coverVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.COVER_VOL
     *
     * @param coverVol the value for down_peri_vol_lst.COVER_VOL
     *
     * @mbg.generated
     */
    public void setCoverVol(String coverVol) {
        this.coverVol = coverVol == null ? null : coverVol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.COVER_ISSUE
     *
     * @return the value of down_peri_vol_lst.COVER_ISSUE
     *
     * @mbg.generated
     */
    public String getCoverIssue() {
        return coverIssue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.COVER_ISSUE
     *
     * @param coverIssue the value for down_peri_vol_lst.COVER_ISSUE
     *
     * @mbg.generated
     */
    public void setCoverIssue(String coverIssue) {
        this.coverIssue = coverIssue == null ? null : coverIssue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.COVER_ISSUE_TOTAL
     *
     * @return the value of down_peri_vol_lst.COVER_ISSUE_TOTAL
     *
     * @mbg.generated
     */
    public String getCoverIssueTotal() {
        return coverIssueTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.COVER_ISSUE_TOTAL
     *
     * @param coverIssueTotal the value for down_peri_vol_lst.COVER_ISSUE_TOTAL
     *
     * @mbg.generated
     */
    public void setCoverIssueTotal(String coverIssueTotal) {
        this.coverIssueTotal = coverIssueTotal == null ? null : coverIssueTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.EXPECT_DATE
     *
     * @return the value of down_peri_vol_lst.EXPECT_DATE
     *
     * @mbg.generated
     */
    public Date getExpectDate() {
        return expectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.EXPECT_DATE
     *
     * @param expectDate the value for down_peri_vol_lst.EXPECT_DATE
     *
     * @mbg.generated
     */
    public void setExpectDate(Date expectDate) {
        this.expectDate = expectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.PUBL_YEAR
     *
     * @return the value of down_peri_vol_lst.PUBL_YEAR
     *
     * @mbg.generated
     */
    public String getPublYear() {
        return publYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.PUBL_YEAR
     *
     * @param publYear the value for down_peri_vol_lst.PUBL_YEAR
     *
     * @mbg.generated
     */
    public void setPublYear(String publYear) {
        this.publYear = publYear == null ? null : publYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.REMARK
     *
     * @return the value of down_peri_vol_lst.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.REMARK
     *
     * @param remark the value for down_peri_vol_lst.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.ATTACHMENT
     *
     * @return the value of down_peri_vol_lst.ATTACHMENT
     *
     * @mbg.generated
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.ATTACHMENT
     *
     * @param attachment the value for down_peri_vol_lst.ATTACHMENT
     *
     * @mbg.generated
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment == null ? null : attachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.ISSUE_TITLE
     *
     * @return the value of down_peri_vol_lst.ISSUE_TITLE
     *
     * @mbg.generated
     */
    public String getIssueTitle() {
        return issueTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.ISSUE_TITLE
     *
     * @param issueTitle the value for down_peri_vol_lst.ISSUE_TITLE
     *
     * @mbg.generated
     */
    public void setIssueTitle(String issueTitle) {
        this.issueTitle = issueTitle == null ? null : issueTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.BEGIN_VOL
     *
     * @return the value of down_peri_vol_lst.BEGIN_VOL
     *
     * @mbg.generated
     */
    public String getBeginVol() {
        return beginVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.BEGIN_VOL
     *
     * @param beginVol the value for down_peri_vol_lst.BEGIN_VOL
     *
     * @mbg.generated
     */
    public void setBeginVol(String beginVol) {
        this.beginVol = beginVol == null ? null : beginVol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.END_VOL
     *
     * @return the value of down_peri_vol_lst.END_VOL
     *
     * @mbg.generated
     */
    public String getEndVol() {
        return endVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.END_VOL
     *
     * @param endVol the value for down_peri_vol_lst.END_VOL
     *
     * @mbg.generated
     */
    public void setEndVol(String endVol) {
        this.endVol = endVol == null ? null : endVol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.BEGIN_ISSUE
     *
     * @return the value of down_peri_vol_lst.BEGIN_ISSUE
     *
     * @mbg.generated
     */
    public String getBeginIssue() {
        return beginIssue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.BEGIN_ISSUE
     *
     * @param beginIssue the value for down_peri_vol_lst.BEGIN_ISSUE
     *
     * @mbg.generated
     */
    public void setBeginIssue(String beginIssue) {
        this.beginIssue = beginIssue == null ? null : beginIssue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.END_ISSUE
     *
     * @return the value of down_peri_vol_lst.END_ISSUE
     *
     * @mbg.generated
     */
    public String getEndIssue() {
        return endIssue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.END_ISSUE
     *
     * @param endIssue the value for down_peri_vol_lst.END_ISSUE
     *
     * @mbg.generated
     */
    public void setEndIssue(String endIssue) {
        this.endIssue = endIssue == null ? null : endIssue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.IMAGE_ADDRESS
     *
     * @return the value of down_peri_vol_lst.IMAGE_ADDRESS
     *
     * @mbg.generated
     */
    public String getImageAddress() {
        return imageAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.IMAGE_ADDRESS
     *
     * @param imageAddress the value for down_peri_vol_lst.IMAGE_ADDRESS
     *
     * @mbg.generated
     */
    public void setImageAddress(String imageAddress) {
        this.imageAddress = imageAddress == null ? null : imageAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.PERI_TYPE
     *
     * @return the value of down_peri_vol_lst.PERI_TYPE
     *
     * @mbg.generated
     */
    public Integer getPeriType() {
        return periType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.PERI_TYPE
     *
     * @param periType the value for down_peri_vol_lst.PERI_TYPE
     *
     * @mbg.generated
     */
    public void setPeriType(Integer periType) {
        this.periType = periType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.PERI_PRICE
     *
     * @return the value of down_peri_vol_lst.PERI_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getPeriPrice() {
        return periPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.PERI_PRICE
     *
     * @param periPrice the value for down_peri_vol_lst.PERI_PRICE
     *
     * @mbg.generated
     */
    public void setPeriPrice(BigDecimal periPrice) {
        this.periPrice = periPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.PERI_TOTAL_PRICE
     *
     * @return the value of down_peri_vol_lst.PERI_TOTAL_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getPeriTotalPrice() {
        return periTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.PERI_TOTAL_PRICE
     *
     * @param periTotalPrice the value for down_peri_vol_lst.PERI_TOTAL_PRICE
     *
     * @mbg.generated
     */
    public void setPeriTotalPrice(BigDecimal periTotalPrice) {
        this.periTotalPrice = periTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.FORE_PRICE
     *
     * @return the value of down_peri_vol_lst.FORE_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getForePrice() {
        return forePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.FORE_PRICE
     *
     * @param forePrice the value for down_peri_vol_lst.FORE_PRICE
     *
     * @mbg.generated
     */
    public void setForePrice(BigDecimal forePrice) {
        this.forePrice = forePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.FORE_TOTAL_PRICE
     *
     * @return the value of down_peri_vol_lst.FORE_TOTAL_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getForeTotalPrice() {
        return foreTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.FORE_TOTAL_PRICE
     *
     * @param foreTotalPrice the value for down_peri_vol_lst.FORE_TOTAL_PRICE
     *
     * @mbg.generated
     */
    public void setForeTotalPrice(BigDecimal foreTotalPrice) {
        this.foreTotalPrice = foreTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.QTY_OF_YEAR
     *
     * @return the value of down_peri_vol_lst.QTY_OF_YEAR
     *
     * @mbg.generated
     */
    public Integer getQtyOfYear() {
        return qtyOfYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.QTY_OF_YEAR
     *
     * @param qtyOfYear the value for down_peri_vol_lst.QTY_OF_YEAR
     *
     * @mbg.generated
     */
    public void setQtyOfYear(Integer qtyOfYear) {
        this.qtyOfYear = qtyOfYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.QTY_OF_VOL
     *
     * @return the value of down_peri_vol_lst.QTY_OF_VOL
     *
     * @mbg.generated
     */
    public Integer getQtyOfVol() {
        return qtyOfVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.QTY_OF_VOL
     *
     * @param qtyOfVol the value for down_peri_vol_lst.QTY_OF_VOL
     *
     * @mbg.generated
     */
    public void setQtyOfVol(Integer qtyOfVol) {
        this.qtyOfVol = qtyOfVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.DAYS_OF_ITEMS
     *
     * @return the value of down_peri_vol_lst.DAYS_OF_ITEMS
     *
     * @mbg.generated
     */
    public Integer getDaysOfItems() {
        return daysOfItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.DAYS_OF_ITEMS
     *
     * @param daysOfItems the value for down_peri_vol_lst.DAYS_OF_ITEMS
     *
     * @mbg.generated
     */
    public void setDaysOfItems(Integer daysOfItems) {
        this.daysOfItems = daysOfItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.PUBL_FREQ_CODE
     *
     * @return the value of down_peri_vol_lst.PUBL_FREQ_CODE
     *
     * @mbg.generated
     */
    public Integer getPublFreqCode() {
        return publFreqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.PUBL_FREQ_CODE
     *
     * @param publFreqCode the value for down_peri_vol_lst.PUBL_FREQ_CODE
     *
     * @mbg.generated
     */
    public void setPublFreqCode(Integer publFreqCode) {
        this.publFreqCode = publFreqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.MARC_ID
     *
     * @return the value of down_peri_vol_lst.MARC_ID
     *
     * @mbg.generated
     */
    public Integer getMarcId() {
        return marcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.MARC_ID
     *
     * @param marcId the value for down_peri_vol_lst.MARC_ID
     *
     * @mbg.generated
     */
    public void setMarcId(Integer marcId) {
        this.marcId = marcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.ADD_TIME
     *
     * @return the value of down_peri_vol_lst.ADD_TIME
     *
     * @mbg.generated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.ADD_TIME
     *
     * @param addTime the value for down_peri_vol_lst.ADD_TIME
     *
     * @mbg.generated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_vol_lst.CATALOG
     *
     * @return the value of down_peri_vol_lst.CATALOG
     *
     * @mbg.generated
     */
    public String getCatalog() {
        return catalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_vol_lst.CATALOG
     *
     * @param catalog the value for down_peri_vol_lst.CATALOG
     *
     * @mbg.generated
     */
    public void setCatalog(String catalog) {
        this.catalog = catalog == null ? null : catalog.trim();
    }
}