package com.gk.webmagic.demo2.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table down_peri_cata_lst
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class DownPeriCataLst{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   期刊编号ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.DOC_ID
     *
     * @mbg.generated
     */
    private String docId;

    /**
     * Database Column Remarks:
     *   站点ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.SITE_ID
     *
     * @mbg.generated
     */
    private Integer siteId;

    /**
     * Database Column Remarks:
     *   文献类型代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.DOC_TYPE_CODE
     *
     * @mbg.generated
     */
    private Integer docTypeCode;

    /**
     * Database Column Remarks:
     *   国家代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.COUNTRY_CODE
     *
     * @mbg.generated
     */
    private String countryCode;

    /**
     * Database Column Remarks:
     *   语种代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.LANG_CODE
     *
     * @mbg.generated
     */
    private String langCode;

    /**
     * Database Column Remarks:
     *   开本代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.BOOK_SIZE_CODE
     *
     * @mbg.generated
     */
    private Integer bookSizeCode;

    /**
     * Database Column Remarks:
     *   载体代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.CARRIER_CODE
     *
     * @mbg.generated
     */
    private Integer carrierCode;

    /**
     * Database Column Remarks:
     *   出版频率代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.PUBL_FREQ_CODE
     *
     * @mbg.generated
     */
    private Integer publFreqCode;

    /**
     * Database Column Remarks:
     *   原系统编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.CALL_NUM
     *
     * @mbg.generated
     */
    private String callNum;

    /**
     * Database Column Remarks:
     *   期刊名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.JOURNAL_TITLE
     *
     * @mbg.generated
     */
    private String journalTitle;

    /**
     * Database Column Remarks:
     *   期刊译名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.TRANS_TITLE
     *
     * @mbg.generated
     */
    private String transTitle;

    /**
     * Database Column Remarks:
     *   其他、原期刊名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.ALTERNATE_TITLE
     *
     * @mbg.generated
     */
    private String alternateTitle;

    /**
     * Database Column Remarks:
     *   责任者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.AUTHOR
     *
     * @mbg.generated
     */
    private String author;

    /**
     * Database Column Remarks:
     *   责任者译名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.TRANS_AUTHOR
     *
     * @mbg.generated
     */
    private String transAuthor;

    /**
     * Database Column Remarks:
     *   单价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.PRICE
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   货币代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.CURRENCY_CODE
     *
     * @mbg.generated
     */
    private Integer currencyCode;

    /**
     * Database Column Remarks:
     *   ISSN
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.ISSN
     *
     * @mbg.generated
     */
    private String issn;

    /**
     * Database Column Remarks:
     *   国内刊号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.PERI_CN_NO
     *
     * @mbg.generated
     */
    private String periCnNo;

    /**
     * Database Column Remarks:
     *   邮发代号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.PERI_ASORD_NO
     *
     * @mbg.generated
     */
    private String periAsordNo;

    /**
     * Database Column Remarks:
     *   出版社名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.PUBLISHER
     *
     * @mbg.generated
     */
    private String publisher;

    /**
     * Database Column Remarks:
     *   出版商
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.COMP_ENTITY
     *
     * @mbg.generated
     */
    private String compEntity;

    /**
     * Database Column Remarks:
     *   原出版社
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.OLD_PUBLISHER
     *
     * @mbg.generated
     */
    private String oldPublisher;

    /**
     * Database Column Remarks:
     *   出版机构代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.PRESS_CODE
     *
     * @mbg.generated
     */
    private String pressCode;

    /**
     * Database Column Remarks:
     *   创刊日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.PUB_DATE
     *
     * @mbg.generated
     */
    private String pubDate;

    /**
     * Database Column Remarks:
     *   出版地
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.PUB_LOC
     *
     * @mbg.generated
     */
    private String pubLoc;

    /**
     * Database Column Remarks:
     *   重印次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.VERSION_TIMES
     *
     * @mbg.generated
     */
    private Integer versionTimes;

    /**
     * Database Column Remarks:
     *   字数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.WORD_COUNT
     *
     * @mbg.generated
     */
    private Integer wordCount;

    /**
     * Database Column Remarks:
     *   分类号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.CLASS_NO
     *
     * @mbg.generated
     */
    private String classNo;

    /**
     * Database Column Remarks:
     *   分类法代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.CLASS_CODE
     *
     * @mbg.generated
     */
    private Integer classCode;

    /**
     * Database Column Remarks:
     *   学科分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.COURSE_CLASS
     *
     * @mbg.generated
     */
    private String courseClass;

    /**
     * Database Column Remarks:
     *   主题词
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.SUBJECT_TERMS
     *
     * @mbg.generated
     */
    private String subjectTerms;

    /**
     * Database Column Remarks:
     *   主题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.SUBJECT
     *
     * @mbg.generated
     */
    private String subject;

    /**
     * Database Column Remarks:
     *   关键词
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.KEYWORDS
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     * Database Column Remarks:
     *   总文章数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.TOTAL_PAPER
     *
     * @mbg.generated
     */
    private Integer totalPaper;

    /**
     * Database Column Remarks:
     *   总下载量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.TOTAL_DOWN
     *
     * @mbg.generated
     */
    private Integer totalDown;

    /**
     * Database Column Remarks:
     *   当前总卷数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.TOTAL_VOLUME
     *
     * @mbg.generated
     */
    private String totalVolume;

    /**
     * Database Column Remarks:
     *   当前总期数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.TOTAL_ISSUE
     *
     * @mbg.generated
     */
    private String totalIssue;

    /**
     * Database Column Remarks:
     *   被引用次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.TIMES_CITED
     *
     * @mbg.generated
     */
    private Integer timesCited;

    /**
     * Database Column Remarks:
     *   引用参考文献数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.REFER_NUM
     *
     * @mbg.generated
     */
    private Integer referNum;

    /**
     * Database Column Remarks:
     *   引用参考文献
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.REFERENCE
     *
     * @mbg.generated
     */
    private String reference;

    /**
     * Database Column Remarks:
     *   影响因子1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.IMPACT_FACTOR1
     *
     * @mbg.generated
     */
    private String impactFactor1;

    /**
     * Database Column Remarks:
     *   影响因子2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.IMPACT_FACTOR2
     *
     * @mbg.generated
     */
    private String impactFactor2;

    /**
     * Database Column Remarks:
     *   收录范围
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.CITATION_INDEX
     *
     * @mbg.generated
     */
    private String citationIndex;

    /**
     * Database Column Remarks:
     *   封面图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.IMAGE_ADDRESS
     *
     * @mbg.generated
     */
    private String imageAddress;

    /**
     * Database Column Remarks:
     *   数据来源
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.DATA_SOURCE
     *
     * @mbg.generated
     */
    private String dataSource;

    /**
     * Database Column Remarks:
     *   全文链接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.FULLTEXT_LINK
     *
     * @mbg.generated
     */
    private String fulltextLink;

    /**
     * Database Column Remarks:
     *   DOI
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.DOI
     *
     * @mbg.generated
     */
    private String doi;

    /**
     * Database Column Remarks:
     *   OCLC
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.OCLC
     *
     * @mbg.generated
     */
    private String oclc;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.ADD_TIME
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   BibTeX
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.BIBTEX
     *
     * @mbg.generated
     */
    private String bibtex;

    /**
     * Database Column Remarks:
     *   MARC类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.MARC_TYPE
     *
     * @mbg.generated
     */
    private String marcType;

    /**
     * Database Column Remarks:
     *   MARC标准
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.MARC_STANDARD
     *
     * @mbg.generated
     */
    private String marcStandard;

    /**
     * Database Column Remarks:
     *   MARC头标区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column down_peri_cata_lst.MARC_HEADER
     *
     * @mbg.generated
     */
    private String marcHeader;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.ID
     *
     * @return the value of down_peri_cata_lst.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.ID
     *
     * @param id the value for down_peri_cata_lst.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.DOC_ID
     *
     * @return the value of down_peri_cata_lst.DOC_ID
     *
     * @mbg.generated
     */
    public String getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.DOC_ID
     *
     * @param docId the value for down_peri_cata_lst.DOC_ID
     *
     * @mbg.generated
     */
    public void setDocId(String docId) {
        this.docId = docId == null ? null : docId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.SITE_ID
     *
     * @return the value of down_peri_cata_lst.SITE_ID
     *
     * @mbg.generated
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.SITE_ID
     *
     * @param siteId the value for down_peri_cata_lst.SITE_ID
     *
     * @mbg.generated
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.DOC_TYPE_CODE
     *
     * @return the value of down_peri_cata_lst.DOC_TYPE_CODE
     *
     * @mbg.generated
     */
    public Integer getDocTypeCode() {
        return docTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.DOC_TYPE_CODE
     *
     * @param docTypeCode the value for down_peri_cata_lst.DOC_TYPE_CODE
     *
     * @mbg.generated
     */
    public void setDocTypeCode(Integer docTypeCode) {
        this.docTypeCode = docTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.COUNTRY_CODE
     *
     * @return the value of down_peri_cata_lst.COUNTRY_CODE
     *
     * @mbg.generated
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.COUNTRY_CODE
     *
     * @param countryCode the value for down_peri_cata_lst.COUNTRY_CODE
     *
     * @mbg.generated
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.LANG_CODE
     *
     * @return the value of down_peri_cata_lst.LANG_CODE
     *
     * @mbg.generated
     */
    public String getLangCode() {
        return langCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.LANG_CODE
     *
     * @param langCode the value for down_peri_cata_lst.LANG_CODE
     *
     * @mbg.generated
     */
    public void setLangCode(String langCode) {
        this.langCode = langCode == null ? null : langCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.BOOK_SIZE_CODE
     *
     * @return the value of down_peri_cata_lst.BOOK_SIZE_CODE
     *
     * @mbg.generated
     */
    public Integer getBookSizeCode() {
        return bookSizeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.BOOK_SIZE_CODE
     *
     * @param bookSizeCode the value for down_peri_cata_lst.BOOK_SIZE_CODE
     *
     * @mbg.generated
     */
    public void setBookSizeCode(Integer bookSizeCode) {
        this.bookSizeCode = bookSizeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.CARRIER_CODE
     *
     * @return the value of down_peri_cata_lst.CARRIER_CODE
     *
     * @mbg.generated
     */
    public Integer getCarrierCode() {
        return carrierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.CARRIER_CODE
     *
     * @param carrierCode the value for down_peri_cata_lst.CARRIER_CODE
     *
     * @mbg.generated
     */
    public void setCarrierCode(Integer carrierCode) {
        this.carrierCode = carrierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.PUBL_FREQ_CODE
     *
     * @return the value of down_peri_cata_lst.PUBL_FREQ_CODE
     *
     * @mbg.generated
     */
    public Integer getPublFreqCode() {
        return publFreqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.PUBL_FREQ_CODE
     *
     * @param publFreqCode the value for down_peri_cata_lst.PUBL_FREQ_CODE
     *
     * @mbg.generated
     */
    public void setPublFreqCode(Integer publFreqCode) {
        this.publFreqCode = publFreqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.CALL_NUM
     *
     * @return the value of down_peri_cata_lst.CALL_NUM
     *
     * @mbg.generated
     */
    public String getCallNum() {
        return callNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.CALL_NUM
     *
     * @param callNum the value for down_peri_cata_lst.CALL_NUM
     *
     * @mbg.generated
     */
    public void setCallNum(String callNum) {
        this.callNum = callNum == null ? null : callNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.JOURNAL_TITLE
     *
     * @return the value of down_peri_cata_lst.JOURNAL_TITLE
     *
     * @mbg.generated
     */
    public String getJournalTitle() {
        return journalTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.JOURNAL_TITLE
     *
     * @param journalTitle the value for down_peri_cata_lst.JOURNAL_TITLE
     *
     * @mbg.generated
     */
    public void setJournalTitle(String journalTitle) {
        this.journalTitle = journalTitle == null ? null : journalTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.TRANS_TITLE
     *
     * @return the value of down_peri_cata_lst.TRANS_TITLE
     *
     * @mbg.generated
     */
    public String getTransTitle() {
        return transTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.TRANS_TITLE
     *
     * @param transTitle the value for down_peri_cata_lst.TRANS_TITLE
     *
     * @mbg.generated
     */
    public void setTransTitle(String transTitle) {
        this.transTitle = transTitle == null ? null : transTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.ALTERNATE_TITLE
     *
     * @return the value of down_peri_cata_lst.ALTERNATE_TITLE
     *
     * @mbg.generated
     */
    public String getAlternateTitle() {
        return alternateTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.ALTERNATE_TITLE
     *
     * @param alternateTitle the value for down_peri_cata_lst.ALTERNATE_TITLE
     *
     * @mbg.generated
     */
    public void setAlternateTitle(String alternateTitle) {
        this.alternateTitle = alternateTitle == null ? null : alternateTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.AUTHOR
     *
     * @return the value of down_peri_cata_lst.AUTHOR
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.AUTHOR
     *
     * @param author the value for down_peri_cata_lst.AUTHOR
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.TRANS_AUTHOR
     *
     * @return the value of down_peri_cata_lst.TRANS_AUTHOR
     *
     * @mbg.generated
     */
    public String getTransAuthor() {
        return transAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.TRANS_AUTHOR
     *
     * @param transAuthor the value for down_peri_cata_lst.TRANS_AUTHOR
     *
     * @mbg.generated
     */
    public void setTransAuthor(String transAuthor) {
        this.transAuthor = transAuthor == null ? null : transAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.PRICE
     *
     * @return the value of down_peri_cata_lst.PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.PRICE
     *
     * @param price the value for down_peri_cata_lst.PRICE
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.CURRENCY_CODE
     *
     * @return the value of down_peri_cata_lst.CURRENCY_CODE
     *
     * @mbg.generated
     */
    public Integer getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.CURRENCY_CODE
     *
     * @param currencyCode the value for down_peri_cata_lst.CURRENCY_CODE
     *
     * @mbg.generated
     */
    public void setCurrencyCode(Integer currencyCode) {
        this.currencyCode = currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.ISSN
     *
     * @return the value of down_peri_cata_lst.ISSN
     *
     * @mbg.generated
     */
    public String getIssn() {
        return issn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.ISSN
     *
     * @param issn the value for down_peri_cata_lst.ISSN
     *
     * @mbg.generated
     */
    public void setIssn(String issn) {
        this.issn = issn == null ? null : issn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.PERI_CN_NO
     *
     * @return the value of down_peri_cata_lst.PERI_CN_NO
     *
     * @mbg.generated
     */
    public String getPeriCnNo() {
        return periCnNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.PERI_CN_NO
     *
     * @param periCnNo the value for down_peri_cata_lst.PERI_CN_NO
     *
     * @mbg.generated
     */
    public void setPeriCnNo(String periCnNo) {
        this.periCnNo = periCnNo == null ? null : periCnNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.PERI_ASORD_NO
     *
     * @return the value of down_peri_cata_lst.PERI_ASORD_NO
     *
     * @mbg.generated
     */
    public String getPeriAsordNo() {
        return periAsordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.PERI_ASORD_NO
     *
     * @param periAsordNo the value for down_peri_cata_lst.PERI_ASORD_NO
     *
     * @mbg.generated
     */
    public void setPeriAsordNo(String periAsordNo) {
        this.periAsordNo = periAsordNo == null ? null : periAsordNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.PUBLISHER
     *
     * @return the value of down_peri_cata_lst.PUBLISHER
     *
     * @mbg.generated
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.PUBLISHER
     *
     * @param publisher the value for down_peri_cata_lst.PUBLISHER
     *
     * @mbg.generated
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.COMP_ENTITY
     *
     * @return the value of down_peri_cata_lst.COMP_ENTITY
     *
     * @mbg.generated
     */
    public String getCompEntity() {
        return compEntity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.COMP_ENTITY
     *
     * @param compEntity the value for down_peri_cata_lst.COMP_ENTITY
     *
     * @mbg.generated
     */
    public void setCompEntity(String compEntity) {
        this.compEntity = compEntity == null ? null : compEntity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.OLD_PUBLISHER
     *
     * @return the value of down_peri_cata_lst.OLD_PUBLISHER
     *
     * @mbg.generated
     */
    public String getOldPublisher() {
        return oldPublisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.OLD_PUBLISHER
     *
     * @param oldPublisher the value for down_peri_cata_lst.OLD_PUBLISHER
     *
     * @mbg.generated
     */
    public void setOldPublisher(String oldPublisher) {
        this.oldPublisher = oldPublisher == null ? null : oldPublisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.PRESS_CODE
     *
     * @return the value of down_peri_cata_lst.PRESS_CODE
     *
     * @mbg.generated
     */
    public String getPressCode() {
        return pressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.PRESS_CODE
     *
     * @param pressCode the value for down_peri_cata_lst.PRESS_CODE
     *
     * @mbg.generated
     */
    public void setPressCode(String pressCode) {
        this.pressCode = pressCode == null ? null : pressCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.PUB_DATE
     *
     * @return the value of down_peri_cata_lst.PUB_DATE
     *
     * @mbg.generated
     */
    public String getPubDate() {
        return pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.PUB_DATE
     *
     * @param pubDate the value for down_peri_cata_lst.PUB_DATE
     *
     * @mbg.generated
     */
    public void setPubDate(String pubDate) {
        this.pubDate = pubDate == null ? null : pubDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.PUB_LOC
     *
     * @return the value of down_peri_cata_lst.PUB_LOC
     *
     * @mbg.generated
     */
    public String getPubLoc() {
        return pubLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.PUB_LOC
     *
     * @param pubLoc the value for down_peri_cata_lst.PUB_LOC
     *
     * @mbg.generated
     */
    public void setPubLoc(String pubLoc) {
        this.pubLoc = pubLoc == null ? null : pubLoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.VERSION_TIMES
     *
     * @return the value of down_peri_cata_lst.VERSION_TIMES
     *
     * @mbg.generated
     */
    public Integer getVersionTimes() {
        return versionTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.VERSION_TIMES
     *
     * @param versionTimes the value for down_peri_cata_lst.VERSION_TIMES
     *
     * @mbg.generated
     */
    public void setVersionTimes(Integer versionTimes) {
        this.versionTimes = versionTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.WORD_COUNT
     *
     * @return the value of down_peri_cata_lst.WORD_COUNT
     *
     * @mbg.generated
     */
    public Integer getWordCount() {
        return wordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.WORD_COUNT
     *
     * @param wordCount the value for down_peri_cata_lst.WORD_COUNT
     *
     * @mbg.generated
     */
    public void setWordCount(Integer wordCount) {
        this.wordCount = wordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.CLASS_NO
     *
     * @return the value of down_peri_cata_lst.CLASS_NO
     *
     * @mbg.generated
     */
    public String getClassNo() {
        return classNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.CLASS_NO
     *
     * @param classNo the value for down_peri_cata_lst.CLASS_NO
     *
     * @mbg.generated
     */
    public void setClassNo(String classNo) {
        this.classNo = classNo == null ? null : classNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.CLASS_CODE
     *
     * @return the value of down_peri_cata_lst.CLASS_CODE
     *
     * @mbg.generated
     */
    public Integer getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.CLASS_CODE
     *
     * @param classCode the value for down_peri_cata_lst.CLASS_CODE
     *
     * @mbg.generated
     */
    public void setClassCode(Integer classCode) {
        this.classCode = classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.COURSE_CLASS
     *
     * @return the value of down_peri_cata_lst.COURSE_CLASS
     *
     * @mbg.generated
     */
    public String getCourseClass() {
        return courseClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.COURSE_CLASS
     *
     * @param courseClass the value for down_peri_cata_lst.COURSE_CLASS
     *
     * @mbg.generated
     */
    public void setCourseClass(String courseClass) {
        this.courseClass = courseClass == null ? null : courseClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.SUBJECT_TERMS
     *
     * @return the value of down_peri_cata_lst.SUBJECT_TERMS
     *
     * @mbg.generated
     */
    public String getSubjectTerms() {
        return subjectTerms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.SUBJECT_TERMS
     *
     * @param subjectTerms the value for down_peri_cata_lst.SUBJECT_TERMS
     *
     * @mbg.generated
     */
    public void setSubjectTerms(String subjectTerms) {
        this.subjectTerms = subjectTerms == null ? null : subjectTerms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.SUBJECT
     *
     * @return the value of down_peri_cata_lst.SUBJECT
     *
     * @mbg.generated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.SUBJECT
     *
     * @param subject the value for down_peri_cata_lst.SUBJECT
     *
     * @mbg.generated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.KEYWORDS
     *
     * @return the value of down_peri_cata_lst.KEYWORDS
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.KEYWORDS
     *
     * @param keywords the value for down_peri_cata_lst.KEYWORDS
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.TOTAL_PAPER
     *
     * @return the value of down_peri_cata_lst.TOTAL_PAPER
     *
     * @mbg.generated
     */
    public Integer getTotalPaper() {
        return totalPaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.TOTAL_PAPER
     *
     * @param totalPaper the value for down_peri_cata_lst.TOTAL_PAPER
     *
     * @mbg.generated
     */
    public void setTotalPaper(Integer totalPaper) {
        this.totalPaper = totalPaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.TOTAL_DOWN
     *
     * @return the value of down_peri_cata_lst.TOTAL_DOWN
     *
     * @mbg.generated
     */
    public Integer getTotalDown() {
        return totalDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.TOTAL_DOWN
     *
     * @param totalDown the value for down_peri_cata_lst.TOTAL_DOWN
     *
     * @mbg.generated
     */
    public void setTotalDown(Integer totalDown) {
        this.totalDown = totalDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.TOTAL_VOLUME
     *
     * @return the value of down_peri_cata_lst.TOTAL_VOLUME
     *
     * @mbg.generated
     */
    public String getTotalVolume() {
        return totalVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.TOTAL_VOLUME
     *
     * @param totalVolume the value for down_peri_cata_lst.TOTAL_VOLUME
     *
     * @mbg.generated
     */
    public void setTotalVolume(String totalVolume) {
        this.totalVolume = totalVolume == null ? null : totalVolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.TOTAL_ISSUE
     *
     * @return the value of down_peri_cata_lst.TOTAL_ISSUE
     *
     * @mbg.generated
     */
    public String getTotalIssue() {
        return totalIssue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.TOTAL_ISSUE
     *
     * @param totalIssue the value for down_peri_cata_lst.TOTAL_ISSUE
     *
     * @mbg.generated
     */
    public void setTotalIssue(String totalIssue) {
        this.totalIssue = totalIssue == null ? null : totalIssue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.TIMES_CITED
     *
     * @return the value of down_peri_cata_lst.TIMES_CITED
     *
     * @mbg.generated
     */
    public Integer getTimesCited() {
        return timesCited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.TIMES_CITED
     *
     * @param timesCited the value for down_peri_cata_lst.TIMES_CITED
     *
     * @mbg.generated
     */
    public void setTimesCited(Integer timesCited) {
        this.timesCited = timesCited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.REFER_NUM
     *
     * @return the value of down_peri_cata_lst.REFER_NUM
     *
     * @mbg.generated
     */
    public Integer getReferNum() {
        return referNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.REFER_NUM
     *
     * @param referNum the value for down_peri_cata_lst.REFER_NUM
     *
     * @mbg.generated
     */
    public void setReferNum(Integer referNum) {
        this.referNum = referNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.REFERENCE
     *
     * @return the value of down_peri_cata_lst.REFERENCE
     *
     * @mbg.generated
     */
    public String getReference() {
        return reference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.REFERENCE
     *
     * @param reference the value for down_peri_cata_lst.REFERENCE
     *
     * @mbg.generated
     */
    public void setReference(String reference) {
        this.reference = reference == null ? null : reference.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.IMPACT_FACTOR1
     *
     * @return the value of down_peri_cata_lst.IMPACT_FACTOR1
     *
     * @mbg.generated
     */
    public String getImpactFactor1() {
        return impactFactor1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.IMPACT_FACTOR1
     *
     * @param impactFactor1 the value for down_peri_cata_lst.IMPACT_FACTOR1
     *
     * @mbg.generated
     */
    public void setImpactFactor1(String impactFactor1) {
        this.impactFactor1 = impactFactor1 == null ? null : impactFactor1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.IMPACT_FACTOR2
     *
     * @return the value of down_peri_cata_lst.IMPACT_FACTOR2
     *
     * @mbg.generated
     */
    public String getImpactFactor2() {
        return impactFactor2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.IMPACT_FACTOR2
     *
     * @param impactFactor2 the value for down_peri_cata_lst.IMPACT_FACTOR2
     *
     * @mbg.generated
     */
    public void setImpactFactor2(String impactFactor2) {
        this.impactFactor2 = impactFactor2 == null ? null : impactFactor2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.CITATION_INDEX
     *
     * @return the value of down_peri_cata_lst.CITATION_INDEX
     *
     * @mbg.generated
     */
    public String getCitationIndex() {
        return citationIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.CITATION_INDEX
     *
     * @param citationIndex the value for down_peri_cata_lst.CITATION_INDEX
     *
     * @mbg.generated
     */
    public void setCitationIndex(String citationIndex) {
        this.citationIndex = citationIndex == null ? null : citationIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.IMAGE_ADDRESS
     *
     * @return the value of down_peri_cata_lst.IMAGE_ADDRESS
     *
     * @mbg.generated
     */
    public String getImageAddress() {
        return imageAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.IMAGE_ADDRESS
     *
     * @param imageAddress the value for down_peri_cata_lst.IMAGE_ADDRESS
     *
     * @mbg.generated
     */
    public void setImageAddress(String imageAddress) {
        this.imageAddress = imageAddress == null ? null : imageAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.DATA_SOURCE
     *
     * @return the value of down_peri_cata_lst.DATA_SOURCE
     *
     * @mbg.generated
     */
    public String getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.DATA_SOURCE
     *
     * @param dataSource the value for down_peri_cata_lst.DATA_SOURCE
     *
     * @mbg.generated
     */
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource == null ? null : dataSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.FULLTEXT_LINK
     *
     * @return the value of down_peri_cata_lst.FULLTEXT_LINK
     *
     * @mbg.generated
     */
    public String getFulltextLink() {
        return fulltextLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.FULLTEXT_LINK
     *
     * @param fulltextLink the value for down_peri_cata_lst.FULLTEXT_LINK
     *
     * @mbg.generated
     */
    public void setFulltextLink(String fulltextLink) {
        this.fulltextLink = fulltextLink == null ? null : fulltextLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.DOI
     *
     * @return the value of down_peri_cata_lst.DOI
     *
     * @mbg.generated
     */
    public String getDoi() {
        return doi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.DOI
     *
     * @param doi the value for down_peri_cata_lst.DOI
     *
     * @mbg.generated
     */
    public void setDoi(String doi) {
        this.doi = doi == null ? null : doi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.OCLC
     *
     * @return the value of down_peri_cata_lst.OCLC
     *
     * @mbg.generated
     */
    public String getOclc() {
        return oclc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.OCLC
     *
     * @param oclc the value for down_peri_cata_lst.OCLC
     *
     * @mbg.generated
     */
    public void setOclc(String oclc) {
        this.oclc = oclc == null ? null : oclc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.ADD_TIME
     *
     * @return the value of down_peri_cata_lst.ADD_TIME
     *
     * @mbg.generated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.ADD_TIME
     *
     * @param addTime the value for down_peri_cata_lst.ADD_TIME
     *
     * @mbg.generated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.UPDATE_TIME
     *
     * @return the value of down_peri_cata_lst.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.UPDATE_TIME
     *
     * @param updateTime the value for down_peri_cata_lst.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.BIBTEX
     *
     * @return the value of down_peri_cata_lst.BIBTEX
     *
     * @mbg.generated
     */
    public String getBibtex() {
        return bibtex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.BIBTEX
     *
     * @param bibtex the value for down_peri_cata_lst.BIBTEX
     *
     * @mbg.generated
     */
    public void setBibtex(String bibtex) {
        this.bibtex = bibtex == null ? null : bibtex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.MARC_TYPE
     *
     * @return the value of down_peri_cata_lst.MARC_TYPE
     *
     * @mbg.generated
     */
    public String getMarcType() {
        return marcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.MARC_TYPE
     *
     * @param marcType the value for down_peri_cata_lst.MARC_TYPE
     *
     * @mbg.generated
     */
    public void setMarcType(String marcType) {
        this.marcType = marcType == null ? null : marcType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.MARC_STANDARD
     *
     * @return the value of down_peri_cata_lst.MARC_STANDARD
     *
     * @mbg.generated
     */
    public String getMarcStandard() {
        return marcStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.MARC_STANDARD
     *
     * @param marcStandard the value for down_peri_cata_lst.MARC_STANDARD
     *
     * @mbg.generated
     */
    public void setMarcStandard(String marcStandard) {
        this.marcStandard = marcStandard == null ? null : marcStandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column down_peri_cata_lst.MARC_HEADER
     *
     * @return the value of down_peri_cata_lst.MARC_HEADER
     *
     * @mbg.generated
     */
    public String getMarcHeader() {
        return marcHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column down_peri_cata_lst.MARC_HEADER
     *
     * @param marcHeader the value for down_peri_cata_lst.MARC_HEADER
     *
     * @mbg.generated
     */
    public void setMarcHeader(String marcHeader) {
        this.marcHeader = marcHeader == null ? null : marcHeader.trim();
    }
}