package com.gk.webmagic.demo2.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_wanfang_unmatch
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class WanFangUnmatch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wanfang_unmatch.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wanfang_unmatch.journal_name
     *
     * @mbg.generated
     */
    private String journalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wanfang_unmatch.article_name
     *
     * @mbg.generated
     */
    private String articleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wanfang_unmatch.article_url
     *
     * @mbg.generated
     */
    private String articleUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wanfang_unmatch.pub_year
     *
     * @mbg.generated
     */
    private String pubYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wanfang_unmatch.cover_issue
     *
     * @mbg.generated
     */
    private String coverIssue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wanfang_unmatch.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wanfang_unmatch.id
     *
     * @return the value of t_wanfang_unmatch.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wanfang_unmatch.id
     *
     * @param id the value for t_wanfang_unmatch.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wanfang_unmatch.journal_name
     *
     * @return the value of t_wanfang_unmatch.journal_name
     *
     * @mbg.generated
     */
    public String getJournalName() {
        return journalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wanfang_unmatch.journal_name
     *
     * @param journalName the value for t_wanfang_unmatch.journal_name
     *
     * @mbg.generated
     */
    public void setJournalName(String journalName) {
        this.journalName = journalName == null ? null : journalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wanfang_unmatch.article_name
     *
     * @return the value of t_wanfang_unmatch.article_name
     *
     * @mbg.generated
     */
    public String getArticleName() {
        return articleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wanfang_unmatch.article_name
     *
     * @param articleName the value for t_wanfang_unmatch.article_name
     *
     * @mbg.generated
     */
    public void setArticleName(String articleName) {
        this.articleName = articleName == null ? null : articleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wanfang_unmatch.article_url
     *
     * @return the value of t_wanfang_unmatch.article_url
     *
     * @mbg.generated
     */
    public String getArticleUrl() {
        return articleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wanfang_unmatch.article_url
     *
     * @param articleUrl the value for t_wanfang_unmatch.article_url
     *
     * @mbg.generated
     */
    public void setArticleUrl(String articleUrl) {
        this.articleUrl = articleUrl == null ? null : articleUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wanfang_unmatch.pub_year
     *
     * @return the value of t_wanfang_unmatch.pub_year
     *
     * @mbg.generated
     */
    public String getPubYear() {
        return pubYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wanfang_unmatch.pub_year
     *
     * @param pubYear the value for t_wanfang_unmatch.pub_year
     *
     * @mbg.generated
     */
    public void setPubYear(String pubYear) {
        this.pubYear = pubYear == null ? null : pubYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wanfang_unmatch.cover_issue
     *
     * @return the value of t_wanfang_unmatch.cover_issue
     *
     * @mbg.generated
     */
    public String getCoverIssue() {
        return coverIssue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wanfang_unmatch.cover_issue
     *
     * @param coverIssue the value for t_wanfang_unmatch.cover_issue
     *
     * @mbg.generated
     */
    public void setCoverIssue(String coverIssue) {
        this.coverIssue = coverIssue == null ? null : coverIssue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wanfang_unmatch.remark
     *
     * @return the value of t_wanfang_unmatch.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wanfang_unmatch.remark
     *
     * @param remark the value for t_wanfang_unmatch.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}