package com.gk.webmagic.demo2.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.gk.webmagic.demo2.model.DownPeriodicalLst;
import com.gk.webmagic.demo2.model.DownPeriodicalLstExample;
import com.gk.webmagic.demo2.model.DownPeriodicalLstWithBLOBs;

public interface DownPeriodicalLstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_periodical_lst
     *
     * @mbg.generated
     */
    long countByExample(DownPeriodicalLstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_periodical_lst
     *
     * @mbg.generated
     */
    int deleteByExample(DownPeriodicalLstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_periodical_lst
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_periodical_lst
     *
     * @mbg.generated
     */
    int insert(DownPeriodicalLstWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_periodical_lst
     *
     * @mbg.generated
     */
    int insertSelective(DownPeriodicalLstWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_periodical_lst
     *
     * @mbg.generated
     */
    List<DownPeriodicalLstWithBLOBs> selectByExampleWithBLOBs(DownPeriodicalLstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_periodical_lst
     *
     * @mbg.generated
     */
    List<DownPeriodicalLst> selectByExample(DownPeriodicalLstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_periodical_lst
     *
     * @mbg.generated
     */
    DownPeriodicalLstWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_periodical_lst
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DownPeriodicalLstWithBLOBs record, @Param("example") DownPeriodicalLstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_periodical_lst
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") DownPeriodicalLstWithBLOBs record, @Param("example") DownPeriodicalLstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_periodical_lst
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DownPeriodicalLst record, @Param("example") DownPeriodicalLstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_periodical_lst
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DownPeriodicalLstWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_periodical_lst
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(DownPeriodicalLstWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table down_periodical_lst
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DownPeriodicalLst record);
    
    /**
     * 根据docId获取某一期刊的所有文章信息
     * @return
     */
    List<Map<String, Object>> selectArticlesByDocId(Map<String, String> map);
}