package com.gk.webmagic.demo2.mapper;

import com.gk.webmagic.demo2.model.WanFangJournalCompare;
import com.gk.webmagic.demo2.model.WanFangJournalCompareExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface WanFangJournalCompareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_journal_compare
     *
     * @mbg.generated
     */
    long countByExample(WanFangJournalCompareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_journal_compare
     *
     * @mbg.generated
     */
    int deleteByExample(WanFangJournalCompareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_journal_compare
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_journal_compare
     *
     * @mbg.generated
     */
    int insert(WanFangJournalCompare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_journal_compare
     *
     * @mbg.generated
     */
    int insertSelective(WanFangJournalCompare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_journal_compare
     *
     * @mbg.generated
     */
    List<WanFangJournalCompare> selectByExample(WanFangJournalCompareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_journal_compare
     *
     * @mbg.generated
     */
    WanFangJournalCompare selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_journal_compare
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WanFangJournalCompare record, @Param("example") WanFangJournalCompareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_journal_compare
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WanFangJournalCompare record, @Param("example") WanFangJournalCompareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_journal_compare
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WanFangJournalCompare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_journal_compare
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WanFangJournalCompare record);
    
    /**
     * 批量插入
     * @param list
     * @return
     */
    int batchInsert(List<WanFangJournalCompare> list);
    
    /**
     * 设置期刊爬取比较状态为完成
     * @param docId
     * @return
     */
    int updateJournalState(Map<String, String> map);
    
    int selectCount();
}