package com.gk.webmagic.demo2.mapper;

import com.gk.webmagic.demo2.model.WanFangUnmatch;
import com.gk.webmagic.demo2.model.WanFangUnmatchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WanFangUnmatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_unmatch
     *
     * @mbg.generated
     */
    long countByExample(WanFangUnmatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_unmatch
     *
     * @mbg.generated
     */
    int deleteByExample(WanFangUnmatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_unmatch
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_unmatch
     *
     * @mbg.generated
     */
    int insert(WanFangUnmatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_unmatch
     *
     * @mbg.generated
     */
    int insertSelective(WanFangUnmatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_unmatch
     *
     * @mbg.generated
     */
    List<WanFangUnmatch> selectByExample(WanFangUnmatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_unmatch
     *
     * @mbg.generated
     */
    WanFangUnmatch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_unmatch
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WanFangUnmatch record, @Param("example") WanFangUnmatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_unmatch
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WanFangUnmatch record, @Param("example") WanFangUnmatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_unmatch
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WanFangUnmatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wanfang_unmatch
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WanFangUnmatch record);
    
    /**
     * 清理未完成比对的未比对成功的数据
     * @return
     */
    int deleteUnfinishUnmatchData();
}